### ISSUE TITLE
[Bug] Warden's sculk ping sound broken

### ISSUE THREAD

**Issue by Treetrain1** [Osmiooo/wildmod#1]
When the warden is spawned, it plays the sculk pinging sound nonstop. It seems that when you make a new sound, it stops playing until it reaches the destination.

Affects 1.18 Beta 0.2

Here's a video showcasing the issue
https://user-images.githubusercontent.com/39657565/145500728-95dfd2c1-680a-4893-a856-5eac7c571d88.mp4

Only this and the Fabric API are installed

**Comment by AlexTheDolphin0** [comment]
I believe this was just fixed in beta-0.3.
