### ISSUE TITLE
Sculk vein dont place on the walls and ceiling

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#101]
![image](https://user-images.githubusercontent.com/82042293/152032985-561421dc-2c72-45ef-9d2a-2e3c3181404b.png)

**Comment by AViewFromTheTop** [comment]
oh god that's gonna be an insane challenge to fix...

**Comment by MerpisMe** [comment]
heads-up, @AViewFromTheTop, we're planning on releasing 0.6 sometime within the next couple of days, however, we can push it back if you need time to work on this. this is basically the last thing on our to-do list before we can release 0.6

**Comment by AViewFromTheTop** [comment]
> heads-up, @AViewFromTheTop, we're planning on releasing 0.6 sometime within the next couple of days but we can push it back if you need time to work on this. this is the last big thing on our to-do list before we release 0.6

I don't think it's actually possible for me to do tbh... The ONLY way I'd get remotely close would be making the Catalyst's radius a sphere instead of circle- which would of course seep into caves. Would that be fine?

**Comment by AViewFromTheTop** [comment]
> > heads-up, @AViewFromTheTop, we're planning on releasing 0.6 sometime within the next couple of days but we can push it back if you need time to work on this. this is the last big thing on our to-do list before we release 0.6
> 
> I don't think it's actually possible for me to do tbh... The ONLY way I'd get remotely close would be making the Catalyst's radius a sphere instead of circle- which would of course seep into caves. Would that be fine?

Even then it'll probably be a nightmare for performance

**Comment by MerpisMe** [comment]
> The ONLY way I'd get remotely close would be making the Catalyst's radius a sphere instead of circle- which would of course seep into caves. Would that be fine?

yeah, doesn't matter much as long as it looks fine. as it currently stands, it looks really weird when sculk spreads up walls because there are no veins

**Comment by AViewFromTheTop** [comment]
![2022-02-06_11 13 00](https://user-images.githubusercontent.com/87103914/152690272-23737b57-ea90-4bb1-b1dd-31c4d0bddc7e.png)
Not final, but looking good. It's still in a circular shape too, but it can indeed spread veins up walls!

**Comment by AViewFromTheTop** [comment]
This saves a ton on performance and all, but the one thing that's stopping me from committing it at the moment is the fact that veins just don't care if they're growing on a Sculk Block horizontally... It's really strange.

**Comment by MerpisMe** [comment]
> This saves a ton on performance and all, but the one thing that's stopping me from committing it at the moment is the fact that veins just don't care if they're growing on a Sculk Block horizontally... It's really strange.

huh.

**Comment by MerpisMe** [comment]
> > This saves a ton on performance and all, but the one thing that's stopping me from committing it at the moment is the fact that veins just don't care if they're growing on a Sculk Block horizontally... It's really strange.
> 
> huh.

by the way, @AViewFromTheTop what's the difference between sculk_untouchable and sculk_unbendable? what does sculk_unbendable do?

**Comment by AViewFromTheTop** [comment]
> by the way, @AViewFromTheTop what's the difference between sculk_untouchable and sculk_unbendable? what does sculk_unbendable do?
> 
> EDIT: OH, does sculk_unbendable define blocks that sculk veins can't "bend" upwards to?

Untouchable is blocks that sculk and sculk veins can't replace or grow on, and you guessed unbendable correctly.

**Comment by AViewFromTheTop** [comment]
Also I think I just got the Vein Placement rewrite done, I'm testing one more time with and without multithreading to make sure it works properly!

**Comment by MerpisMe** [comment]
> Also I think I just got the Vein Placement rewrite done, I'm testing one more time with and without multithreading to make sure it works properly!

oh, awesome! by the way, we're really close to getting the biome working!

**Comment by AViewFromTheTop** [comment]
> oh, awesome! by the way, we're really close to getting the biome working! (by which i mean that @AlexTheDolphin0 has gotten the biome working and is now tweaking and fixing it)

YOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
Btw, how exactly will we get the Sculk Growths to work in the Deep Dark? If there's a way to call methods only upon generation that'd be easy, but otherwise we'll have to rely on likely inaccurate Sculk Growths in the biome.

**Comment by MerpisMe** [comment]
> Btw, how exactly will we get the Sculk Growths to work in the Deep Dark? If there's a way to call methods only upon generation that'd be easy, but otherwise we'll have to rely on likely inaccurate Sculk Growths in the biome.

i'm thinking alex is using the sphere api to generate them so hopefully they shouldn't be too inaccurate. i'll have to ask him though

**Comment by AViewFromTheTop** [comment]
Does the latest commit resolve this?

**Comment by MerpisMe** [comment]
> Does the latest commit resolve this?

will check

**Comment by MerpisMe** [comment]
> Does the latest commit resolve this?

yep! amazing work!!
