### ISSUE TITLE
Stop Rest of Animation Syncing

### ISSUE THREAD

**Issue by AViewFromTheTop** [Osmiooo/wildmod#102]
ROTATIONS/TRANSLATIONS TO SET TO DEFAULT:

EMERGING -
- [x] body.yaw
- [x] head.yaw
- [x] left_leg.pitch
- [x] right_leg.pitch
- [x] left_ear.yaw
- [x] right_ear.yaw

SNIFFING -
- [x] body.pivotY
- [x] left_leg.pivotY
- [x] left_leg.pitch
- [x] right_leg.pivotY
- [x] right_leg.pitch
- [x] left_arm.pivotY
- [x] left_arm.pivotZ
- [x] right_arm.pivotY
- [x] right_arm.pivotZ
- [x] left_ear.yaw
- [x] right_ear.yaw

**Comment by AViewFromTheTop** [comment]
@MerpisMe still busy (why do i feel the need to keep saying this,) but do you happen to also know the rounded length of the emerge animation? It's kinda strange how it freezes and snaps into the idle animation since idk the proper timing for it

**Comment by MerpisMe** [comment]
> @MerpisMe still busy (why do i feel the need to keep saying this,) but do you happen to also know the rounded length of the emerge animation? It's kinda strange how it freezes and snaps into the idle animation since idk the proper timing for it

should be 149 ticks. by the way, all i do to find it is look through the animation and find the highest `to:` value, then multiply that by 20

**Comment by MerpisMe** [comment]
also, i'm not entirely sure as to what you're asking me to do with this issue

**Comment by AViewFromTheTop** [comment]
> also, i'm not entirely sure as to what you're asking me to do with this issue

set the values that have tasks to their defaults in the listed animation, it stops the weird syncing for those transformations/rotations during said animation

**Comment by AViewFromTheTop** [comment]
@MerpisMe I just added the roaring cooldown and the two variables needed for the roaring animation

**Comment by AViewFromTheTop** [comment]
@MerpisMe nvm i think i fixed it
half the stuff just had to be set to 0
