### ISSUE TITLE
Warden doesn't spawn if doMobSpawning is false

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#105]
Despite having a gamerule solely dedicated to it (`wardenSpawns`) the warden does not spawn if `doMobSpawning` is false. This is VERY unhelpful for testing. Also, sculk shriekers don't work properly when it's false, possibly as a result of the warden not spawning

**Comment by AViewFromTheTop** [comment]
Merp, you're the one who suggested that it should follow the gamerule

**Comment by AViewFromTheTop** [comment]
#70

**Comment by MerpisMe** [comment]
> Merp, you're the one who suggested that it should follow the gamerule

yeah i know, but then i suggested we give it its own gamerule, and i must have forgotten to say that it should be removed from the overall mobspawning rule

**Comment by AViewFromTheTop** [comment]
> > Merp, you're the one who suggested that it should follow the gamerule
> 
> yeah i know, but then i suggested we give it its own gamerule, and i must have forgotten to say that it should be removed from the overall mobspawning rule

oh
