### ISSUE TITLE
Warden is completely oblivious

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#107]
The Warden basically just completely ignores the you if you just stand next to it and don't make any vibrations. If possible, when its anger level is past a certain point (once it's angry, so just before roaring), it should attack the player if they are within 0.15 blocks of distance to it.
- [ ] Make Warden attack its target if its target is within 0.15 blocks of distance to it (and it's angry)

**Comment by AViewFromTheTop** [comment]
I’m busy atm, but this should hopefully be easy

Just requires a new goal, and checking suspicion of all entities in a 2x2 area (probably 2.5x2.5 to accommodate for its hitbox)

**Comment by MerpisMe** [comment]
> (probably 2.5x2.5 to accommodate for its hitbox)

would 2.15x2.15 be possible, or does it only work in integers?

**Comment by AViewFromTheTop** [comment]
> > (probably 2.5x2.5 to accommodate for its hitbox)
> 
> would 2.15x2.15 be possible, or does it only work in integers?

idk, it only integers work then it'd have to be 2x2 or 3x3
