### ISSUE TITLE
Sculk does not spread up walls

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#109]
![2022-02-03_21 22 04](https://user-images.githubusercontent.com/27739930/152466811-2b9f0eeb-190e-456d-9d28-212f96202b23.png)

**Comment by AViewFromTheTop** [comment]
I'm gonna be busy today, just a heads-up.
I think the easiest way to make it spread up walls is to just add in sub-checks within sculkCheck (if that's what I named it) and have it replace every replaceable & air-exposed block on its way up the wall.

**Comment by AViewFromTheTop** [comment]
Just started thinking about this again and it could result in a Sculk Dupe. Maybe I could make sculkCheck return the first replacable & exposed block instead of replacing each once, that'd make more sense.

**Comment by MerpisMe** [comment]
> Just started thinking about this again and it could result in a Sculk Dupe. Maybe I could make sculkCheck return the first replacable & exposed block instead of replacing each one, that'd make more sense.

oh, i also forgot to mention this by the way, sculk vein placement is pretty broken right now and it seems to entirely ignore the whole "break if above sculk" rule

**Comment by AViewFromTheTop** [comment]
> oh, that reminds me, i also forgot to mention that sculk vein placement is pretty broken right now and it seems to entirely ignore the whole "break if above sculk" rule

aaaaaaaaAAAAAAAAAAAAAAAAAA WHY
i can't update one freaking thing anymore without it breaking
bruh

**Comment by AViewFromTheTop** [comment]
@MerpisMe Aight, I won't be busy again for hopefully another three hours, I'll see what I can do with the sculk spreading and strange vein placement. By the way, are there any new Warden bugs?

**Comment by MerpisMe** [comment]
> @MerpisMe Aight, I won't be busy again for hopefully another three hours, I'll see what I can do with the sculk spreading and strange vein placement. By the way, are there any new Warden bugs?

no, actually! i just released a third snapshot last night and so far we've only been getting reports for things like sculk itself. i think the warden's finally finished!

**Comment by AViewFromTheTop** [comment]
> no, actually! i just released a third snapshot last night and so far we've only been getting reports for things like sculk itself. i think the warden's finally finished!

Should I intentionally break something with the Warden so I can fix a warden bug instead

**Comment by MerpisMe** [comment]
> > no, actually! i just released a third snapshot last night and so far we've only been getting reports for things like sculk itself. i think the warden's finally finished!
> 
> Should I intentionally break something with the Warden so I can fix a warden bug instead

i mean if you're desperate for something to work on, you could set up the animation calls for frogs

**Comment by AViewFromTheTop** [comment]
>EDIT: or actually, could you try to optimize fireflies' ai a bit? apparently they're super laggy. also they seem to always follow the same goal when spawned near each other

I think we actually need to switch back to the Area Effect Cloud idea, ModBay posted that there were some new references to fireflies in one of the Betas, and that naming all points towards fireflies being controlled by something like an Area Effect Cloud

Also I don't really think there's a way to optimize their AI, we just need to try out the particle cloud thing

**Comment by AViewFromTheTop** [comment]
>also they seem to always follow the same goal when spawned near each other

I have no frickin idea why this happens, it's just one of those strange Minecraft things I guess

**Comment by MerpisMe** [comment]
> ModBay posted that there were some new references to fireflies in one of the Betas, and that naming all points towards fireflies being controlled by something like an Area Effect Cloud

the naming is actually for rtx; specular, diffuse filter, and diffuse are all PBR terms

**Comment by AViewFromTheTop** [comment]
> the naming is actually for rtx; specular, diffuse filter, and diffuse are all PBR terms

oh. I didn't notice that. Probably because I didn't know. And probably because I don't care much about RTX. Despite having an RTX graphics card. I just use it for the performance. I like playing Minecraft with other 4 fps.

**Comment by MerpisMe** [comment]
> > the naming is actually for rtx; specular, diffuse filter, and diffuse are all PBR terms
> 
> I just use it for the performance. I like playing Minecraft with other 4 fps.

top 10 most relatable quotes of the century

**Comment by AViewFromTheTop** [comment]
> top 10 most relatable quotes of the century

Not for anyone on Bedrock though (unless you're on a server on Switch)

**Comment by AViewFromTheTop** [comment]
bruh I just opened up my testing world and i just see "you died" with a Warden sniffing in the distance

**Comment by MerpisMe** [comment]
> > top 10 most relatable quotes of the century
> 
> Not for anyone on Bedrock though (unless you're on a server on Switch)

yeah true. unless you're trying to navigate the ui. then you'll be crying.

**Comment by AViewFromTheTop** [comment]
> yeah true. unless you're trying to navigate the ui. then you'll be crying.

don't even get me started on that
I love the Marketplace to randomly try out free maps and i can't even see the name of the map
Then I have to try on my phone, but Apple has no idea what "good screen size" means and it becomes a pain either way

**Comment by MerpisMe** [comment]
> bruh I just opened up my testing world and i just see "you died" with a Warden sniffing in the distance

OH, actually, i do have something that you could potentially do whenever you can-- could you set up the calls for an attack animation? theoretically it should be as simple as setting the animation to be equal to a variable that just gets added to the idle animation

**Comment by AViewFromTheTop** [comment]
> OH, actually, i do have something that you could potentially do whenever you can-- could you set up the calls for an attack animation? theoretically it should be as simple as setting the animation to be equal to a variable that just gets added to the idle animation

i'm kinda lost here, would I just do the usual sendEntityStatus() followed by setting up the typical animationProgress stuff, or does it need something different?

**Comment by MerpisMe** [comment]
> but Apple has no idea what "good screen size" means and it becomes a pain either way

it's also a pain that minecraft only lets you set a fixed aspect ratio for the screen safe area. i REALLY hope they end up adding the ability to adjust your vertical and horizontal screen safe area and also position it. the funny thing is that these DO exist already, they just don't have any way to configure them in game for whatever reason

**Comment by MerpisMe** [comment]
> > OH, actually, i do have something that you could potentially do whenever you can-- could you set up the calls for an attack animation? theoretically it should be as simple as setting the animation to be equal to a variable that just gets added to the idle animation
> 
> i'm kinda lost here, would I just do the usual sendEntityStatus() followed by setting up the typical animationProgress stuff, or does it need something different?

yep, same stuff. you don't need to worry about the second part, that's all for me to do

**Comment by AViewFromTheTop** [comment]
I've been looking at the SculkGrower code for an hour and can't find a SINGLE place where veins would be allowed to grow on top of Sculk. Why is it happening?

**Comment by AViewFromTheTop** [comment]
@BluePhoenixLOL @MerpisMe I found the cause of the issue: The references to the Sculk Jaw broke the tags. I'll have to delete it, but in TWMPLUS you can copy the same folder structure. I'll go do it for you guys since it's probably confusing.
