### ISSUE TITLE
Warden Overlay Tweaks v2

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#110]
- [x] Possibly have the overlay opacity lerp between light levels instead of using a cosine function (not sure if possible/feasible)
- [x] Sky light should not affect overlay's opacity (https://twitter.com/kingbdogz/status/1313449116068917249)

**Comment by AViewFromTheTop** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO NOT AGAIN

**Comment by AViewFromTheTop** [comment]
ok seriously though, second one is easy, and for the first... I have no clue what "lerp" is.
Is she your sister?

**Comment by MerpisMe** [comment]
> ok seriously though, second one is easy, and for the first... I have no clue what "lerp" is. Is she your sister?

linear interpolate
![image](https://user-images.githubusercontent.com/27739930/152609983-dacb196a-acec-4d76-964a-c72124c03cf3.png)

**Comment by MerpisMe** [comment]
> > ok seriously though, second one is easy, and for the first... I have no clue what "lerp" is. Is she your sister?
> 
> linear interpolate ![image](https://user-images.githubusercontent.com/27739930/152609983-dacb196a-acec-4d76-964a-c72124c03cf3.png)

this would probably require storing the previous light level somewhere separate, which may be an issue for performance/organization

**Comment by AViewFromTheTop** [comment]
> this would probably require storing the previous light level somewhere separate, which may be an issue for performance/organization

I don't even know how to use lerp so I'd need an example first, do you know by any chance where this is used in MC

**Comment by AViewFromTheTop** [comment]
> I don't even know how to use lerp so I'd need an example first, do you know by any chance where this is used in MC

NVM, just saw something in MangroveBoatEntity that uses it

**Comment by MerpisMe** [comment]
> > I don't even know how to use lerp so I'd need an example first, do you know by any chance where this is used in MC
> 
> NVM, just saw something in MangroveBoatEntity that uses it

glow squid also use it when fading in after being attacked, which would probably be far more helpful to you since it's already half done there

**Comment by AViewFromTheTop** [comment]
> glow squid also use it when fading in after being attacked, which would probably be far more helpful to you since it's already half done there

yeah idk if I can do it

**Comment by MerpisMe** [comment]
> > glow squid also use it when fading in after being attacked, which would probably be far more helpful to you since it's already half done there
> 
> yeah idk if I can do it

alright then fair enough. would you be able to at least smooth the transition out a bit? it's near instant at the moment

**Comment by AViewFromTheTop** [comment]
Well uh
I got it working, but here's the catch:
When you remove a light source the Warden's bright again, and it fades to dark

**Comment by AViewFromTheTop** [comment]
> Well uh I got it working, but here's the catch: When you remove a light source the Warden's bright again, and it fades to dark

I fixed that just now (EASY) but how do I get it to fade when the light lowers? As of now it just snaps to dark.

**Comment by MerpisMe** [comment]
> I fixed that just now (EASY) but how do I get it to fade when the light lowers? As of now it just snaps to dark.

by this do you mean it snaps to dark if a light source is placed?

**Comment by AViewFromTheTop** [comment]
> by this do you mean it snaps to dark if a light source is placed?

yeah, but removing one works perfectly

**Comment by AViewFromTheTop** [comment]
Just committed what I have atm so you can see if I'm doing something wrong

**Comment by MerpisMe** [comment]
> > by this do you mean it snaps to dark if a light source is placed?
> 
> yeah, but removing one works perfectly

tbh, that's fine, it'll be unnoticeable and we can just call it a feature (unless the fade to bright is really long and noticeable, in which case maybe shorten the duration of the fade so it's not as easy to see the difference)

**Comment by AViewFromTheTop** [comment]
> > > by this do you mean it snaps to dark if a light source is placed?
> > 
> > 
> > yeah, but removing one works perfectly
> 
> tbh, that's fine, it'll be unnoticeable and we can just call it a feature (unless the fade to bright is really long and noticeable, in which case maybe shorten the duration of the fade so it's not as easy to see the difference)

im an idiot I forgot to actually change the lastLightLevel
bruh bruh bruh bruh

**Comment by MerpisMe** [comment]
> > > > by this do you mean it snaps to dark if a light source is placed?
> > > 
> > > 
> > > yeah, but removing one works perfectly
> > 
> > 
> > tbh, that's fine, it'll be unnoticeable and we can just call it a feature (unless the fade to bright is really long and noticeable, in which case maybe shorten the duration of the fade so it's not as easy to see the difference)
> 
> im an idiot I forgot to actually change the lastLightLevel bruh bruh bruh bruh

LOL

**Comment by AViewFromTheTop** [comment]
> LOL

nope that actually makes it worse somehow, wth am I doing wrong

**Comment by MerpisMe** [comment]
> > LOL
> 
> nope that actually makes it worse somehow, wth am I doing wrong

here, just leave it i'll test it in a sec

**Comment by MerpisMe** [comment]
> > > LOL
> > 
> > 
> > nope that actually makes it worse somehow, wth am I doing wrong
> 
> here, just leave it i'll test it in a sec

THIS IS PERFECT
it doesnt really matter that there's no transition when a light source is placed since it happens at the exact same time that the light appears

**Comment by AViewFromTheTop** [comment]
@MerpisMe there's a problem with this, I makes the Warden dark even in a light level of 1.
I just found another solution that properly interpolates the value based on the light level and if it's higher or not, it won't have the fancy dimming once the light source is removed, but it also won't be buggy, and it doesn't dramatically shift how much the overlay glows between light levels. Should I commit that version instead?

**Comment by AViewFromTheTop** [comment]
Actually I was wrong, it still does have the cool dimming. I’ll just commit it then.

**Comment by MerpisMe** [comment]
oh ok cool

**Comment by AViewFromTheTop** [comment]
> oh ok cool

now it's acting buggy
i stg every time im about to commit something

**Comment by MerpisMe** [comment]
> > oh ok cool
> 
> now it's acting buggy i stg every time im about to commit something

what's it doing? depending on the severity of it i'd say just commit it anyway and say it's a feature lol

**Comment by AViewFromTheTop** [comment]
> what's it doing? depending on the severity of it i'd say just commit it anyway and say it's a feature lol

nope i just fixed it. Basically if we want to have the warden to continue changing it's value and slowly glow after light is removed, it'll be buggy, so I sadly had to remove it.

**Comment by AViewFromTheTop** [comment]
Closing this as we probably have the best solution we'll get at the moment, unless someone else knows how to do this better
