### ISSUE TITLE
Warden Vibration delay is longer than Sculk Sensor

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#111]
https://user-images.githubusercontent.com/27739930/152630113-3f9e2810-bfda-40a6-9ba1-9901cd3175f9.mp4

**Comment by AViewFromTheTop** [comment]
That’s because the vibration is sending to its head, so it’s technically two blocks further than the Sculk Sensor. I would like to keep it in, but considering how easy the fix is and the fact that pretty much all vibrations would be delayed, I’ll fix it soon.
