### ISSUE TITLE
Warden resets anger erroneously 

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#113]
![195EA7E6-26E5-4371-8436-665D7F0BDF4B](https://user-images.githubusercontent.com/27739930/152645824-3e324df4-5ae8-4fc4-ac23-0e393362d5ad.jpeg)
we're better off just removing it
![6885CA80-B262-49BB-B30A-5BA9625811B0](https://user-images.githubusercontent.com/27739930/152645843-cf9b6554-0b56-4754-acea-a5f36a6c4dda.jpeg)

**Comment by AViewFromTheTop** [comment]
So I just remove the suspicion tick checking then?

**Comment by AViewFromTheTop** [comment]
> So I just remove the suspicion tick checking then?

Or removing deleting the suspicion for the specific entity it kills

**Comment by MerpisMe** [comment]
> > So I just remove the suspicion tick checking then?
> 
> Or remove deleting the suspicion for the specific entity it kills

whichever thing you did that made it check for an entity within a radius, yeah
