### ISSUE TITLE
Warden does not fall if there are no blocks in front of him

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#114]
https://user-images.githubusercontent.com/82042293/152648618-d25e097b-4256-44f2-8597-4b920c530ea5.mp4

Warden does not fall if there are no blocks in front of him, but on mclive2021 you can see that he should fall, because he is blind

**Comment by AViewFromTheTop** [comment]
This is definitely important, but I can't find out what part of pathfinding controls this...
