### ISSUE TITLE
Warden’s Left Arm Gets Stuck If It Detects A Vibration While Sniffing

### ISSUE THREAD

**Issue by AViewFromTheTop** [Osmiooo/wildmod#115]

**Comment by AViewFromTheTop** [comment]
> yeah i noticed this, not entirely sure as to why

actually the left arm doesn't move at all with the walk animation, it's pretty much glued to its torso

**Comment by MerpisMe** [comment]
> > yeah i noticed this, not entirely sure as to why
> 
> actually the left arm doesn't move at all with the walk animation, it's pretty much glued to its torso

oh. great.

**Comment by AViewFromTheTop** [comment]
> > > yeah i noticed this, not entirely sure as to why
> > 
> > 
> > actually the left arm doesn't move at all with the walk animation, it's pretty much glued to its torso
> 
> oh. great.

This is why: this.left_arm.pitch = (AnimationAPI.easeOutSine(t * 0f, t * 0.24f, -120f / j, attackTime) +
AnimationAPI.easeInOutSine(t * 0.24f, t * 0.44f, 120f / j, attackTime));
                  
It's using the attack animation timer instead of the normal walking stuff

**Comment by MerpisMe** [comment]
> > > > yeah i noticed this, not entirely sure as to why
> > > 
> > > 
> > > actually the left arm doesn't move at all with the walk animation, it's pretty much glued to its torso
> > 
> > 
> > oh. great.
> 
> This is why: this.left_arm.pitch = (AnimationAPI.easeOutSine(t * 0f, t * 0.24f, -120f / j, attackTime) + AnimationAPI.easeInOutSine(t * 0.24f, t * 0.44f, 120f / j, attackTime));
> 
> It's using the attack animation timer instead of the normal walking stuff

crap. mobile editor moment lol
