### ISSUE TITLE
Warden doesn't get vibration if the player drop an item, but the sculk sensor gets

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#117]
https://user-images.githubusercontent.com/82042293/152679711-bc4a462e-4979-4c00-9461-a6b5420cd1fe.mp4

**Comment by MerpisMe** [comment]
the warden's missing a few vibration types
the ones i've noticed are
- [ ] Finish eating/drinking
- [ ] Item landing

**Comment by AViewFromTheTop** [comment]
> the warden's missing a few vibration types the ones i've noticed are
> 
> * [ ]  Finish eating/drinking
> * [ ]  Item landing

That may be easy to add, but the reason the Warden won't get those vibraitons is because they're not caused by LivingEntities- the mixin was setup to exclude vibrations without a tied LivingEntity from the start.

**Comment by AViewFromTheTop** [comment]
@MerpisMe adding this would make the Warden extremely easy to cheese with a piston and a redstone clock, I don't think it's worth adding if it'll ruin the purpose of the Warden.

**Comment by MerpisMe** [comment]
> @MerpisMe adding this would make the Warden extremely easy to cheese with a piston and a redstone clock, I don't think it's worth adding if it'll ruin the purpose of the Warden.

**Comment by MerpisMe** [comment]
> @MerpisMe adding this would make the Warden extremely easy to cheese with a piston and a redstone clock, I don't think it's worth adding if it'll ruin the purpose of the Warden.
> Edit: Actually I'm gonna make a custom frequency map for the Warden and use that instead of the Sculk sensor one. That way it'll be able to follow items, but not pistons or the like.

though, if that's the case, how come eating doesn't send a vibration despite being made by a living entity?

**Comment by AViewFromTheTop** [comment]
> though, if that's the case, how come eating doesn't send a vibration despite being made by a living entity?

likely an oversight on Mojang's side

**Comment by MerpisMe** [comment]
> > though, if that's the case, how come eating doesn't send a vibration despite being made by a living entity?
> 
> likely an oversight on Mojang's side, they probably didn't care because the Warden wasn't added yet, which would be the only reason they'd ever need to tie the GameEvent to an entity

oh okay, i thought it was something like "oh but technically it's not the living entity making the vibration, it's the food" lol
