### ISSUE TITLE
Figure out how to modify scale with animations

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#121]
Frogs need a better system to control both their tongue scale and their croaking body (why is it not just called sac i dont get that)

The current system we use for the croaking causes a duplicate version of it to appear inside of the body (visible when opening its mouth) and also not move with the body.

- [ ] Figure out how to control scale via keyframes
- [ ] Figure out how to control each axis with scaling

**Comment by MerpisMe** [comment]
@AViewFromTheTop you think we could use the method you were talking about with switching body parts out for specific animations for the frog's eat animation? For now, at least. It looks extremely weird when the mouth opens and the tongue stays static, so maybe we have two versions of the tongue that are made invisible and swapped out for one another

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop you think we could use the method you were talking about with switching body parts out for specific animations for the frog's eat animation? For now, at least. It looks extremely weird when the mouth opens and the tongue stays static, so maybe we have two versions of the tongue that are made invisible and swapped out for one another

In that case I wonder why not just make the tongue invisible until the mouth opens?

**Comment by MerpisMe** [comment]
> > @AViewFromTheTop you think we could use the method you were talking about with switching body parts out for specific animations for the frog's eat animation? For now, at least. It looks extremely weird when the mouth opens and the tongue stays static, so maybe we have two versions of the tongue that are made invisible and swapped out for one another
> 
> In that case I wonder why not just make the tongue invisible until the mouth opens? it's never usually seen unless the eating animation's played anyway

hmm, true, but doing that would also make it look weird when there's no tongue at the beginning of the animation when it opens its mouth. could be worth a shot to do it like that though
