### ISSUE TITLE
Prevent Warden Despawning when nametagged?

### ISSUE THREAD

**Issue by Skeithh** [Osmiooo/wildmod#127]
I don't know if its intended or not, but I was sad to find out that wardens despawn even after being nametagged. I'd love for this to not be the case so I can have a constant threat to my homies wandering around my property.

**Comment by AViewFromTheTop** [comment]
Now that is an interesting question, I don't think any of us have actually thought of that.
The main thing is, that would imply the Warden's behavior changes based on whether it's nametagged or not, which conflicts with the implied (and confirmed) lore of the Warden we've gotten so far.

I don't know if the other team members would agree with my idea, but I propose that nametagged Wardens would still be able to dig underground, but instead of being removed, they'll wait for another vibration and emerge again.
@MerpisMe @BluePhoenixLOL what do you think?

**Comment by MerpisMe** [comment]
> Now that is an interesting question, I don't think any of us have actually thought of that. The main thing is, that would imply the Warden's behavior changes based on whether it's nametagged or not, which conflicts with the implied (and confirmed) lore of the Warden we've gotten so far.
> 
> I don't know if the other team members would agree with my idea, but I propose that nametagged Wardens would still be able to dig underground, but instead of being removed, they'll wait for another vibration and emerge again. @MerpisMe @BluePhoenixLOL what do you think?

sure, i like that. the only thing is that this prevents people from making it a "display" kind of thing. i'll make a new issue detailing one potential solution to this

**Comment by MerpisMe** [comment]
> > Now that is an interesting question, I don't think any of us have actually thought of that. The main thing is, that would imply the Warden's behavior changes based on whether it's nametagged or not, which conflicts with the implied (and confirmed) lore of the Warden we've gotten so far. However, following the lore side of things conflicts with the gameplay side of things, as no mob despawns when nametagged- we don't know if the Warden will be an exception to this rule or not.
> > I don't know if the other team members would agree with my idea, but I propose that nametagged Wardens would still be able to dig underground, but instead of being removed, they'll wait for another vibration and emerge again. @MerpisMe @BluePhoenixLOL what do you think?
> 
> No, i think the warden may be like enderdragon, you cant nametag it at all

this is a limitation, not a feature. the ender dragon is made up of several entities.

**Comment by MerpisMe** [comment]
> > sure, i like that. the only thing is that this prevents people from making it a "display" kind of thing. i'll make a new issue detailing one potential solution to this
> 
> I don't think Wardens are really meant to be a display thing though, as kingbdogz has mentioned repeatedly that it's a "natural disaster" as opposed to a simple hostile or passive mob. I think my idea balances this out a bit, allowing you to take advantage of the Warden's strength (having it wait for a vibration,) while also making it clear that the Warden isn't a pet.

fair enough, I like that then

**Comment by MerpisMe** [comment]
> > fair enough, I like that then
> 
> Quick thing we'd have to consider- how would the Warden look while underground? Would it just be invisible?

![troll_gradual](https://user-images.githubusercontent.com/27739930/153071903-6343159c-8296-4a13-87fd-81b868899e4e.gif)

**Comment by MerpisMe** [comment]
> so I can have a constant threat to my homies wandering around my property.
as for this, @Skeithh you could always just hide sculk shriekers and sensors under your floor and the Warden will spawn that way

**Comment by AViewFromTheTop** [comment]
Testing this right now!

**Comment by AViewFromTheTop** [comment]
> Testing this right now!

ok this is probably one of the best ideas we've ever had

**Comment by Skeithh** [comment]
Ah well- The main reason I asked for no warden despawn was specifically to have it present more as a display thing in certain areas as well >> But it is understandable if that goes against the design idea. Unless it can only come out of the ground in specific types of blocks (i.e only emerge from stone types/sculk/deepslate?)

I definitely do think the "hide underground" thing is a really cool feature though- Glad my question regarding no despawning brought upon that idea d:

**Comment by AViewFromTheTop** [comment]
> Ah well- The main reason I asked for no warden despawn was specifically to have it present more as a display thing in certain areas as well >> But it is understandable if that goes against the design idea. Unless it can only come out of the ground in specific types of blocks (i.e only emerge from stone types/sculk/deepslate?)
> 
> I definitely do think the "hide underground" thing is a really cool feature though- Glad my question regarding no despawning brought upon that idea d:

Wardens won't be able to dig if they're on a block they normally can't spawn on as of the latest commit. If a Warden is on a piston or on an upper half-slab it shouldn't be able to dig. I think the easiest way to prevent the Warden from digging is to place it on a half-slab and make sure that air is underneath it, then you'll be able to display it!
Thanks for the inspiration for the second idea as well!

**Comment by Skeithh** [comment]
Awesome! Thank you :D

**Comment by AViewFromTheTop** [comment]
Just added it!
