### ISSUE TITLE
Warden should not be able to dig everywhere

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#128]
The Warden should not dig if it's standing on blocks with the warden_unspawnable tag. The way it currently works, the Warden can dig in any scenario as long as it hasn't received a vibration in 60 seconds. Including in the air.

I don't see any issue with this from a gameplay perspective, really, since the only thing it would do is make the player's life harder by making the Warden unable to despawn. The only issue I can see is performance since the Warden would have to constantly be checking if the block it's standing on is suitable to dig on.

**Comment by AViewFromTheTop** [comment]
> The only issue I can see is performance since the Warden would have to constantly be checking if the block it's standing on is suitable to dig on.

oh boy
another timer

**Comment by AViewFromTheTop** [comment]
this is unrelated but I was searching a question about cosine and sin, and a freaking government hotline showed up as the first search result wth

**Comment by MerpisMe** [comment]
> this is unrelated but I was searching a question about cosine and sine, and a freaking government hotline showed up as the first search result wth

LOL
what have you been up to, lunade? 👀

**Comment by AViewFromTheTop** [comment]
> > this is unrelated but I was searching a question about cosine and sine, and a freaking government hotline showed up as the first search result wth
> 
> LOL what have you been up to, lunade? 👀

the only things i've been searching up are math-related questions or stuff about minecraft modding, with the occasional dog question

**Comment by AViewFromTheTop** [comment]
btw I'm testing Sculk Growths using tags rn

**Comment by MerpisMe** [comment]
> btw I'm testing Sculk Growths using tags rn

oh sick, good luck

**Comment by AViewFromTheTop** [comment]
> > btw I'm testing Sculk Growths using tags rn
> 
> oh sick, good luck

Works perfectly. Gonna optimize it a bit, and then commit- it doesn't change the current behavior at all, either.
