### ISSUE TITLE
Warden Angry After hit

### ISSUE THREAD

**Issue by BluePhoenixLOL** [Osmiooo/wildmod#129]
I Feel The Warden Should get angry and roar then chase the player when hit.

**Comment by MerpisMe** [comment]
> I Feel The Warden Should get angry and roar then chase the player when hit.

yeah this can just be done by raising the suspicion level of attacking the warden to something really high (i agree, it currently takes about 8 hits before the warden roars)

**Comment by MerpisMe** [comment]
> Should the suspicion for attacking a Warden just be set to 45 because that would solve the issue instantly honestly

i think it should be 23 since it should take two hits
