### ISSUE TITLE
Stinky Thief Mode Broken When Above World Height Limit

### ISSUE THREAD

**Issue by AViewFromTheTop** [Osmiooo/wildmod#135]
i cant believe the stinky thieves can play the mod above y320

gonna fix later, just wanted a funny bug report for it

**Comment by BluePhoenixLOL** [comment]
its SUPER DUPER laggy tho

**Comment by AViewFromTheTop** [comment]
> its SUPER DUPER laggy tho

i designed it to be that way, stinky thieves don't deserve to run minecraft at fast speed
