### ISSUE TITLE
Beta 0.6 Changelog

### ISSUE THREAD

**Issue by AViewFromTheTop** [Osmiooo/wildmod#136]
Putting this up so we can hopefully provide players with a more descriptive changelog for the next update, and so we can also track our progress.
**FEEL FREE TO EDIT AND ADD STUFF THAT ISN'T LISTED!**

**WARDEN**
**Added new Warden animations & visual improvements:**
- Emerge
- Dig
- Sniff
- Attack
- Tendril Clicking
- Head Rolling
- Souls now pulse along with the heartbeat sound
- Tendrils now glow alongside detecting a vibration
- The main Warden overlay now properly inversely matches the block light level
- Has a new pulsating Dot overlay
- Updated texture

**Warden changes & bugfixes:**
- Updated hitbox
- Wardens now have new sounds
- Players now have a minimum suspicion value of 3 per vibration, other entities have a minimum of 2
- Wardens get more suspicious of a player based on vibration frequency
- Wardens can now detect items falling and eating
- Wardens can no longer move towards a vibration until the vibration reaches its head (Vibrations are finally delayed)
- Vibrations reach the Warden faster as it gets angrier
- Warden vibrations now work properly on servers
- Sniffing adds a suspicion value of 7 now
- Wardens will sniff after wandering for a short period of time
- Wardens will now roar after being hit twice- attacking them significantly raises their suspicion.
- Wardens now always move towards the location they just sniffed instead of staying frozen
- Warden now chase their targetEntity for 3 seconds after roaring
- Wardens will now attack entities that stand next to it (and have a suspicion level higher than 7)
- Wardens can no longer attack each other or become suspicious of each other
- Wardens now avoid directly walking into lava, fire, and powder snow
- Wardens stay around in peaceful mode, but will not attack or sniff.
- Nametagged Wardens will hide underground instead of despawning, and will re-emerge once they detect a vibration.
- Wardens can no longer dig and despawn on non-solid blocks and pistons.
- The Warden now emits Darkness.
- Changed heartbeat timing to match Minecraft Live
- Wardens can now wander around properly

**DEEP DARK**
- Generates below y0
- Includes various Sculk Growths

**SCULK**
**Completely rewrote Sculk Growths:**
- Sculk growths now expand once a radius is filled with Sculk
- Outer Sculk growths (past 24 blocks) now spread in a vein-like manner
- Sculk growth performance has been heavily optimized
- Sculk veins can now grow on all sides of blocks
- Sculk can now grow on walls and ceilings instead of only floors
- Sculk activator placement has been revised, and can now be modified with the use of datapacks
- Multithreading for Sculk Growths has been removed
- Added new gamerule "sculkStopsSculkCheck" to improve performance with massive Sculk Growths, this is off by default.

**Sculk Shriekers:**
- The radius for inflicting Darkness upon a player has been significantly increased.
- Revised Warden summoning; Wardens can't emerge if it's daytime and they're exposed to the sky, they'll instead whine underground. Wardens can now also be summoned 24 blocks away from another, instead of 48.

**DARKNESS**
- The Darkness effect now controls the close, closer, and closest sounds.
- Changes made to fog rendering due to the implementation of the Darkness effect will now only be applied while Darkness is active.

**FROGS**
- New and improved eating animation
- Now walk at the intended speed
- Can now eat while in water
- Longer eating cooldown
- No longer eat fireflies

**FIREFLIES**
- Now Have spawn egg and spawn in swamps
- Now use quaternion rendering
- Have new AI

**OTHER FIXES**
- Mangrove Swamps no longer crash the game.
- Numerous texture changes and model fixes
- Mud bricks and mud have new sounds!
- Added rooted mud, a new block that is mud + mangrove roots, you can craft it by combining those in a crafting table.

- Added a new secret mode that only four people will ever see.

**Comment by MerpisMe** [comment]
not gonna add this to the list, but i think my new mud brick texture is genuinely the best block texture we have in the mod, i dunno what it is about it
![2022-02-11_21 46 37](https://user-images.githubusercontent.com/27739930/153695518-29f7490c-5f92-47ff-acda-50d07cf6142a.png)
also warden photobomb lol

**Comment by AViewFromTheTop** [comment]
> not gonna add this to the list, but i think this new mud brick texture is genuinely the best block texture we have in the mod, i dunno what it is about it ![2022-02-11_21 46 37](https://user-images.githubusercontent.com/27739930/153695518-29f7490c-5f92-47ff-acda-50d07cf6142a.png) also warden photobomb lol

it does look cool though

**Comment by AViewFromTheTop** [comment]
@MerpisMe don't forget this for 0.6

**Comment by MerpisMe** [comment]
> @MerpisMe don't forget this for 0.6

yep, just copied this onto the changelog
