### ISSUE TITLE
Putting a Goat next to a Frog named Osmiooo crashes the game.

### ISSUE THREAD

**Issue by BluePhoenixLOL** [Osmiooo/wildmod#138]
https://user-images.githubusercontent.com/80720298/153726773-57afa31b-8403-4fb0-ac65-eb54d76ef591.mp4

**Comment by AViewFromTheTop** [comment]
What?

**Comment by BluePhoenixLOL** [comment]
> I see what happened. Goat eating was implemented wrong. I'll fix it.

cool xD
