### ISSUE TITLE
Warden uses secret texture when it is near an Osmiooo warden

### ISSUE THREAD

**Issue by Treetrain1** [Osmiooo/wildmod#141]
This only happens when both wardens are rendered

https://user-images.githubusercontent.com/39657565/153767702-5b1ea691-fc0f-468c-9fdf-8fd39e444c4b.mp4

**Comment by AViewFromTheTop** [comment]
> Relates to #63

It doesn't relate to 63, it's more of the animation syncing bug.
I have an idea of how to fix this, but I'll get around to it once I'm done working on my pipe mod for today.
