### ISSUE TITLE
Sculk Sensors should drop similarly to other sculk blocks

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#143]
Although yet unconfirmed, I'm almost 100% certain that sculk sensors are intended to only drop themselves if broken with silktouch, and drop exp otherwise. It wouldn't make much sense for sensors to be the only thing that doesn't follow this rule, especially considering the fact that sensors are also technically living. We could also put the current functionality behind a gamerule if decided upon.

Would this even be possible? Surely we'd need a mixin to do it, but I have no idea how to go about doing that.

**Comment by AViewFromTheTop** [comment]
I'm quite certain it's intentional. It can't be a coincidence that we've never seen this functionality AND Sensors are meant to be used with redstone, whereas Shriekers and Catalysts are primarily meant for the Deep Dark and likely won't do much with redstone.

**Comment by MerpisMe** [comment]
> I'm quite certain it's intentional. It can't be a coincidence that we've never seen this functionality AND Sensors are meant to be used with redstone, whereas Shriekers and Catalysts are primarily meant for the Deep Dark and likely won't do much with redstone.

sure, but it still doesn't make a whole lot of sense for sensors to drop if broken normally; they're made of the same stuff and are living. i'm fairly certain it's only the way it is currently because they probably hadn't decided that sculk stuff should drop exp when they added the sensor in the 1.17 snapshots

**Comment by MerpisMe** [comment]
> I don't think it will, if you look at the footage of mc live 2021, you can see kingbdogz breaking a sculk sensor without silk touch and getting it

as for this, that seems like an oversight on their end, my theory is just that they didn't add in the changes they made to sculk to the sensors at this point in time. it's very likely that the decision for sculk to drop exp was last-minute, especially considering the fact that the mobs they kill still drop exp, effectively doubling the amount of exp you'd get (overpowered)

**Comment by AViewFromTheTop** [comment]
> > I don't think it will, if you look at the footage of mc live 2021, you can see kingbdogz breaking a sculk sensor without silk touch and getting it
> 
> as for this, that seems like an oversight on their end, my theory is just that they didn't add in the changes they made to sculk to the sensors at this point in time. it's very likely that the decision for sculk to drop exp was last-minute, especially considering the fact that the mobs they kill still drop exp, effectively doubling the amount of exp you'd get (overpowered)

I think that'll stay in, kingbdogz said Sculk was a replacement for the autofarms using zombified piglins where they'd drop XP regardless of how they died, which is a HUGE XP source. Using Sculk in farms will be more challenging as you'd need some sort of stone generator (how the heck will there be one in the Nether btw? It must be able to replace basalt then,) and you'd need to bring the sculk to the player. It's more of a farm enhancement than XP replacement, so they can fix a long-lasting bug without insane backlash while also giving a new feature a good use

**Comment by AViewFromTheTop** [comment]
> i suppose so, but i don't see much logic in the fact that they should drop themselves simply because they're a redstone component. mojang would explicitly mention that they're a special case if they were supposed to be, and they have yet to. it seems like the current sensor we have is in fact just an unfinished version. after all, they did add the functionality of standing on them to activate them after the fact, so it's entirely possible that they plan to make them act similarly to the other sculk blocks.
> 
> also, sculk has a pretty substantial redstone usage too, and it doesn't drop itself without silktouch

I think I may have worded my arguments a little strange. Let's think about this in terms of game progression:
-Player spawns, gets tools, etc
-Player finds redstone, finds out it can open doors. Player gets swarmed by zombies, and now wants to make a trap.
-Player uses trapdoors and pressure plates, but it doesn't work too well.
-Player later finds Deep Dark, sees redstone particles on Sensors. They try to break it, and they're able to use it freely. However, they can't bring normal Sculk or Catalysts with them.
-Player can now enhance their redstone contraptions.
**-Player later gets enough XP to get Silk Touch and get other Sculk Blocks**
**-Player can now obtain even more XP**

Redstone is almost always found first before Diamonds and Obsidian, just like how Sensors are obtainable for Redstone, before other Sculk blocks are obtainable for enchanting points/XP. It seems to me that Sensors are meant to go alongside the semi-early-game progression, to help teach players about Redstone and learn the mechanics of the Deep Dark. On the other hand, the other Sculk blocks must be obtained later when the player learns about XP and enchanting, as they ALREADY would've realized Sculk drops XP when they tried to grab it earlier.

**Comment by MerpisMe** [comment]
> > i suppose so, but i don't see much logic in the fact that they should drop themselves simply because they're a redstone component. mojang would explicitly mention that they're a special case if they were supposed to be, and they have yet to. it seems like the current sensor we have is in fact just an unfinished version. after all, they did add the functionality of standing on them to activate them after the fact, so it's entirely possible that they plan to make them act similarly to the other sculk blocks.
> > also, sculk has a pretty substantial redstone usage too, and it doesn't drop itself without silktouch
> 
> I think I may have worded my arguments a little strange. Let's think about this in terms of game progression: -Player spawns, gets tools, etc -Player finds redstone, finds out it can open doors. Player gets swarmed by zombies, and now wants to make a trap. -Player uses trapdoors and pressure plates, but it doesn't work too well. -Player later finds Deep Dark, sees redstone particles on Sensors. They try to break it, and they're able to use it freely. However, they can't bring normal Sculk or Catalysts with them. -Player can now enhance their redstone contraptions. **-Player later gets enough XP to get Silk Touch and get other Sculk Blocks** **-Player can now obtain even more XP**
> 
> Redstone is almost always found first before Diamonds and Obsidian, just like how Sensors are obtainable for Redstone, before other Sculk blocks are obtainable for enchanting points/XP. It seems to me that Sensors are meant to go alongside the semi-early-game progression, to help teach players about Redstone and learn the mechanics of the Deep Dark. On the other hand, the other Sculk blocks must be obtained later when the player learns about XP and enchanting, as they ALREADY would've realized Sculk drops XP when they tried to grab it earlier.

sure, but on the other hand breaking a sensor is extremely risky and is likely to get the player killed. making them drop themselves would promote this, which would lead to the player being killed numerous times. it's unlikely that they'd be willing to go back there until they have better gear if they do end up getting killed.

**Comment by AViewFromTheTop** [comment]
> sure, but on the other hand breaking a sensor is extremely risky and is likely to get the player killed. making them drop themselves would promote this, which would lead to the player being killed numerous times. it's unlikely that they'd be willing to go back there until they have better gear if they do end up getting killed. i don't think that it's a good idea making sensors so easily accessible; the deep dark isn't supposed to be explored until later-game, and that much is clearly evidenced by the hugely foreboding city structure and soul fire stuff, all of which are normally only accessible after having been to the nether

ummmmmmmm
super mario

**Comment by MerpisMe** [comment]
> sure, but on the other hand breaking a sensor is extremely risky and is likely to get the player killed. making them drop themselves would promote this, which would lead to the player being killed numerous times. it's unlikely that they'd be willing to go back there until they have better gear if they do end up getting killed. i don't think that it's a good idea making sensors so easily accessible; the deep dark isn't supposed to be explored until later-game, and that much is clearly evidenced by the hugely foreboding city structure and soul fire stuff, all of which are normally only accessible after having been to the nether.

on top of all of that, sculk itself in the lore isn't meant to be used as redstone; it only interacts with redstone. sure, other sculk stuff may not be as important, but they all tie into redstone to some extent and it's not so much of "this thing does more stuff" as it is "these all do stuff, how could you put them all together?"
like kingbdogz said, the sculk stuff is all meant to be interconnected with each other; promoting taking only one part of it goes against that

**Comment by MerpisMe** [comment]
> > sure, but on the other hand breaking a sensor is extremely risky and is likely to get the player killed. making them drop themselves would promote this, which would lead to the player being killed numerous times. it's unlikely that they'd be willing to go back there until they have better gear if they do end up getting killed. i don't think that it's a good idea making sensors so easily accessible; the deep dark isn't supposed to be explored until later-game, and that much is clearly evidenced by the hugely foreboding city structure and soul fire stuff, all of which are normally only accessible after having been to the nether.
> 
> on top of all of that, sculk itself in the lore isn't meant to be used as redstone; it only interacts with redstone. sure, other sculk stuff may not be as important, but they all tie into redstone to some extent and it's not so much of "this thing does more stuff" as it is "these all do stuff, how could you put them all together?" like kingbdogz said, the sculk stuff is all meant to be interconnected with each other; promoting taking only one part of it goes against that

plus, if a player breaks the sensors and they drop but nothing else does, the player will think that everything else is simply unobtainable and just won't try again. however, if we make them all require silktouch, it might lead to the player experimenting with them and seeing that they work with redstone, so they surely must be obtainable somehow.

**Comment by AViewFromTheTop** [comment]
> plus, if a player breaks the sensors and they drop but nothing else does, the player will think that everything else is simply unobtainable and just won't try again. however, if we make them all require silktouch, it might lead to the player experimenting with them and seeing that they work with redstone, so they surely must be obtainable somehow.

what you don't know is that sculk sensors are made of rock and not sculk there you go case solved im totally not realizing my arguments were not the best and i totally dont agree with you

**Comment by MerpisMe** [comment]
i didnt close that excuse me github

**Comment by AViewFromTheTop** [comment]
> i didnt close that excuse me github

oh hey you closed it

**Comment by MerpisMe** [comment]
> what you don't know is that sculk sensors are made of rock and not sculk there you go case solved im totally not realizing my arguments were not the best and i totally dont agree with you

also, your arguments were good from a designer standpoint, it makes sense if you think about it that way because you yourself have already interacted with the stuff numerous times. also i'm secretly jeb and i knew what i was talking about the whole time so ha ha

**Comment by BluePhoenixLOL** [comment]
nah

**Comment by AViewFromTheTop** [comment]
> > nah
> 
> read before saying anything, we've already decided on it also you cant just say no and not explain your position on a topic like this ._. also you're outnumbered ![7C4154DC-C2A5-4DC6-A591-A2F42B78A638](https://user-images.githubusercontent.com/27739930/153932297-22a7d3dd-7dc2-42d3-a2c1-45f99aa1868d.jpeg)

Two things:
1. You voted for yourself
2. You presented the arguments in an extremely biased manner

**Comment by BluePhoenixLOL** [comment]
> > i suppose so, but i don't see much logic in the fact that they should drop themselves simply because they're a redstone component. mojang would explicitly mention that they're a special case if they were supposed to be, and they have yet to. it seems like the current sensor we have is in fact just an unfinished version. after all, they did add the functionality of standing on them to activate them after the fact, so it's entirely possible that they plan to make them act similarly to the other sculk blocks.
> > also, sculk has a pretty substantial redstone usage too, and it doesn't drop itself without silktouch
> 
> I think I may have worded my arguments a little strange. Let's think about this in terms of game progression: -Player spawns, gets tools, etc -Player finds redstone, finds out it can open doors. Player gets swarmed by zombies, and now wants to make a trap. -Player uses trapdoors and pressure plates, but it doesn't work too well. -Player later finds Deep Dark, sees redstone particles on Sensors. They try to break it, and they're able to use it freely. However, they can't bring normal Sculk or Catalysts with them. -Player can now enhance their redstone contraptions. **-Player later gets enough XP to get Silk Touch and get other Sculk Blocks** **-Player can now obtain even more XP**
> 
> Redstone is almost always found first before Diamonds and Obsidian, just like how Sensors are obtainable for Redstone, before other Sculk blocks are obtainable for enchanting points/XP. It seems to me that Sensors are meant to go alongside the semi-early-game progression, to help teach players about Redstone and learn the mechanics of the Deep Dark. On the other hand, the other Sculk blocks must be obtained later when the player learns about XP and enchanting, as they ALREADY would've realized Sculk drops XP when they tried to grab it earlier.
> 
> Edit: My main point is that Sensors being easier to obtain matches Minecraft's progression, and having other Sculk blocks being obtainable later helps the player once they learn about the main problem with enchanting. I don't think anyone would use enchantments before redstone on their first time playing Minecraft, honestly.

yes

**Comment by AViewFromTheTop** [comment]
aaaaaaaaaAAAAAAAAAAAAA THIS LOOKS SO MUCH BETTER HOW DID I NEVER KNOW THERE WAS A DARK MODE

**Comment by MerpisMe** [comment]
> aaaaaaaaaAAAAAAAAAAAAA THIS LOOKS SO MUCH BETTER HOW DID I NEVER KNOW THERE WAS A DARK MODE

LOL you were using light mode this whole time?? i feel so bad for your poor eyes

**Comment by AViewFromTheTop** [comment]
> we should add this and then just remove it if it's deconfirmed, it's not like it's incredibly difficult to implement/remove again

done

**Comment by MerpisMe** [comment]
after playing around with this, i must say that it feels REALLY good in practice. it makes breaking sensors really satisfying.

by the way, if it isn't already like this, we should make catalysts, sensors, and shriekers all drop differing levels of exp based on their hierarchal position in usefulness to fending off intruders. 
- catalysts should drop the least (despite being the reason the sculk is there to begin with, they don't really do a whole lot to prevent intruders)
- sensors should be in the middle (they're among the main few tools that the warden uses in order to seek out and kill intruders)
- shriekers should drop the most (because they summon the warden which pretty much makes them the most dangerous)
