### ISSUE TITLE
Deep Dark notes 

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#149]
- [x] Reduce the number of catalysts & sensors; it looks a bit messy
- [x] Decrease max size of sculk patches & make them generate with large blobs instead of with noise (looks messy and ultimately doesn't really work incredibly well admittedly)
- [ ] Figure out how to stop bats from flying into the biome and spawning the Warden (we MUST blacklist bats from creating any vibrations)
- [x] Remove springs
- [ ] Remove aquifers
- [ ] Remove mineshafts from generation
- [x] Fix Sculk Veins; Too many, looks too messy
- [ ] Add glow lichen-like sculk vein generation
- [ ] Add Deep Dark Cities (For 0.7 or later)
- [ ] Add ambient sounds & loops (we could use the soul sand valley ones as a placeholder)

**Comment by MerpisMe** [comment]
> * [ ]  Add ambient sounds & loops (we could use the soul sand valley ones as a placeholder)

**Comment by AViewFromTheTop** [comment]
> > * [ ]   Add ambient sounds & loops (because i hate myself)

i mean half of that's done with the Warden darkness, it player the closer sound every so often

**Comment by MerpisMe** [comment]
> > > * [ ]    Add ambient sounds & loops (because i hate myself)
> 
> i mean half of that's done with the Warden darkness, it player the closer sound every so often

yeah but if you sneak through without creating vibrations it's gotta have some other sounds

**Comment by AViewFromTheTop** [comment]
> yeah but if you sneak through without creating vibrations it's gotta have some other sounds

car crash sounds that play randomly

**Comment by MerpisMe** [comment]
> > yeah but if you sneak through without creating vibrations it's gotta have some other sounds
> 
> car crash sounds that play randomly

🧠

**Comment by MerpisMe** [comment]
> * [ ] Decrease max size of sculk patches & make them generate with large blobs instead of with noise (looks messy and ultimately doesn't really work incredibly well admittedly)

@AViewFromTheTop i know you spent a lot of time trying to get it working this way, but even i have to admit that it looks really messy in tighter caves. i think maybe we should make it generate large blobs surrounding catalysts and then have several smaller blobs bordering the edges of them or something
OR, we generate a large scale noisemap and generate blobs of sculk wherever the values are black to dictate the falloff of the blobs, and then generate a smaller scale noisemap on top of it as an octave system in order to make the falloff look like the blobs are becoming smaller and more scattered

**Comment by AViewFromTheTop** [comment]
> also because everyone is complaining about it even though this is just temporary

Here's what I'd tell them:
Quit complaining, quit whining. Be grateful the Sculk Patches even exist. Get over yourselves, or figure out how to do it on your own. I'm not your babysitter, I'm not your dad, I'm not your uncle, I'm not your best friend, I'm not a Genie. I'm a modder.

**Comment by AViewFromTheTop** [comment]
> also because everyone is complaining about it even though this is just temporary

I've gotta be honest, I'm tired of how often people complain about this stuff. I literally began learning Java in mid-November, I can't do 2,000 frickin things at once, and my code isn't going to be perfect. I only knew extremely basic LUA before-hand, which I hadn't even done for two years prior to starting up with Java- I've been learning this entire time.
Now, if they quit complaining and realize that this is a MOD, and that I am not a WIZARD, and that I have things to DO, and that they should be GREATFUL that Sculk Patches are even a THING, then I'll consider it. Otherwise, it's gonna stay as a local commit on my PC.

**Comment by AViewFromTheTop** [comment]
> EDIT: what happened to your comment

i deleted it because it was too dramatic

**Comment by MerpisMe** [comment]
> > EDIT: what happened to your comment
> 
> i deleted it because it was too dramatic

dramatic or not, it's true. you shouldn't feel like you're being dramatic when you express your concerns because in the end you also have a voice that matters and it's imperative that you make it known if you have any grievances with anything

**Comment by AViewFromTheTop** [comment]
![2022-02-15_11 43 13](https://user-images.githubusercontent.com/87103914/154108503-f095c3e5-3777-4e02-ba21-eca211e0fef2.png)
here's why blob generation sucks

**Comment by AViewFromTheTop** [comment]
![2022-02-15_11 49 49](https://user-images.githubusercontent.com/87103914/154109619-68b6fc2f-ff77-4f16-bb51-83b876bc1716.png)
I tweaked blob generation a bit (using higher ends of noise,) I don't get how this isn't messier than the current iteration

**Comment by MerpisMe** [comment]
> ![2022-02-15_11 49 49](https://user-images.githubusercontent.com/87103914/154109619-68b6fc2f-ff77-4f16-bb51-83b876bc1716.png) I tweaked blob generation a bit (using higher ends of noise,) I don't get how this isn't messier than the current iteration

i think the issue is the fact that it's messy. using feature blobs should make it waaaay less messy

**Comment by AViewFromTheTop** [comment]
> i think the issue is the fact that noise is messy. using feature blobs should make it waaaay less messy

idk what feature blobs are but if you mean what's used to generate clay, how would we do the veins?
We'd just have to port SculkGrower in its entirety to the feature then. I'd prefer to just stick with the current iteration because it's fun to look at and unique, and will give out the same result consistently if you use the same seed.

**Comment by MerpisMe** [comment]
> idk what feature blobs are but if you mean what's used to generate clay, how would we do the veins? We'd just have to port SculkGrower in its entirety to the feature then. I'd prefer to just stick with the current iteration because it's fun to look at and unique, and will give out the same result consistently if you use the same seed.

i was thinking something like the blobs that form on bedrock. but also, thats fair tbh, it's just kinda messy i guess (and people outside of our team will complain if it's messy)

**Comment by AViewFromTheTop** [comment]
> it's just kinda messy i guess (and people outside of our team will complain if it's messy)

it's literally an alien corruption that takes over caves and spreads from death

**Comment by AViewFromTheTop** [comment]
> i was thinking something like the blobs that form on bedrock

that's SculkGrower

**Comment by MerpisMe** [comment]
> that's SculkGrower

oh

**Comment by MerpisMe** [comment]
> porting SculkGrower to SculkPatchFeature is that it will NOT be the same every time you use the seed
oh.

> On top of that, it'll be nearly impossible to get Sculk to generate on walls and ceilings.

as for this, i'm not entirely sure how to feel about the sculk stuff being on the walls and ceiling. it pretty harshly contrasts what we've seen. for the most part i think it'd be fine if there's occasionally sculk on the walls, but i don't think there should ever be any on ceilings

> I personally think the best solution is to port a few things over from SculkGrower, but only use it to generate a small patch around the Catalyst and that's it. That way we can still keep the cool noise Sculk, while making Catalysts a little more visually pleasing.

sure, i like that idea. we probably should have the blobs be relatively large though, since it looks a bit weird for there to be so much exposed deepslate right next to a catalyst

**Comment by AViewFromTheTop** [comment]
Unrelated, but I wanted to bring this up. That "portal" in the center of the Deep Dark looks like the Warden kinda, with the tendrils, right?

Why does it have The Hollowed's ears instead of the Warden's tendrils?

**Comment by AViewFromTheTop** [comment]
> Unrelated, but I wanted to bring this up. That "portal" in the center of the Deep Dark looks like the Warden kinda, with the tendrils, right?
> 
> Why does it have The Hollowed's ears instead of the Warden's tendrils?

Found a screenshot https://i.ytimg.com/vi/XdkNlHrJEoI/maxresdefault.jpg

**Comment by AViewFromTheTop** [comment]
> Unrelated, but I wanted to bring this up. That "portal" in the center of the Deep Dark looks like the Warden kinda, with the tendrils, right?

Also if "Mysterious Frame" from Bedrock is indeed this portal-like thing, there's a Mysterious Frame Slot. If that makes it into the final game, chances are, some of the unique loot in the Deep Dark is for using the frames.

**Comment by MerpisMe** [comment]
> > Unrelated, but I wanted to bring this up. That "portal" in the center of the Deep Dark looks like the Warden kinda, with the tendrils, right?
> > Why does it have The Hollowed's ears instead of the Warden's tendrils?
> 
> Found a screenshot https://i.ytimg.com/vi/XdkNlHrJEoI/maxresdefault.jpg

yeah i dunno, i noticed that too. it also looks kinda like the design on chiseled deepslate, if only slightly

**Comment by MerpisMe** [comment]
> > Unrelated, but I wanted to bring this up. That "portal" in the center of the Deep Dark looks like the Warden kinda, with the tendrils, right?
> 
> Also if "Mysterious Frame" from Bedrock is indeed this portal-like thing, there's a Mysterious Frame Slot. If that makes it into the final game, chances are, some of the unique loot in the Deep Dark is for using the frames.

maybe? it doesn't look like it really has anywhere for there to be a slot though

**Comment by AViewFromTheTop** [comment]
> Also if "Mysterious Frame" from Bedrock is indeed this portal-like thing, there's a Mysterious Frame Slot. If that makes it into the final game, chances are, some of the unique loot in the Deep Dark is for using the frames.

This also goes back to the whole "Stalker" idea with totems scattered around the Deep Dark. What were the totems used for? Would make sense if they were needed to unlock that frame/portal thing. Just now, the Warden's there instead of the Stalker, and the totems are now different items inside of chests.

**Comment by MerpisMe** [comment]
> > Also if "Mysterious Frame" from Bedrock is indeed this portal-like thing, there's a Mysterious Frame Slot. If that makes it into the final game, chances are, some of the unique loot in the Deep Dark is for using the frames.
> 
> This also goes back to the whole "Stalker" idea with totems scattered around the Deep Dark. What were the totems used for? Would make sense if they were needed to unlock that frame/portal thing. Just now, the Warden's there instead of the Stalker, and the totems are now different items inside of chests.

huh. that's true. i never really thought about that

**Comment by AViewFromTheTop** [comment]
> maybe? it doesn't look like it really has anywhere for there to be a slot though

There's another block called "minecraft:mysterious_frame_slot" in BE as well
Video: https://www.youtube.com/watch?v=jbslVmZ1rAA
On the wiki: https://minecraft.fandom.com/wiki/Bedrock_Edition_1.19.0

**Comment by MerpisMe** [comment]
> > maybe? it doesn't look like it really has anywhere for there to be a slot though
> 
> There's another block called "minecraft:mysterious_frame_slot" in BE as well Video: https://www.youtube.com/watch?v=jbslVmZ1rAA On the wiki: https://minecraft.fandom.com/wiki/Bedrock_Edition_1.19.0 I've seen a few videos about it, not just that one

oh! huh.

**Comment by MerpisMe** [comment]
> > > maybe? it doesn't look like it really has anywhere for there to be a slot though
> > 
> > 
> > There's another block called "minecraft:mysterious_frame_slot" in BE as well Video: https://www.youtube.com/watch?v=jbslVmZ1rAA On the wiki: https://minecraft.fandom.com/wiki/Bedrock_Edition_1.19.0 I've seen a few videos about it, not just that one
> 
> oh! huh.

by the way, have you seen this?
https://twitter.com/Cojomax99/status/1493624167907926022/photo/1
i'm pissed off by this. the overlay uses a completely different texture because the different colours on the mouth were not visible on the bedrock screenshots. also look directly under the bottom left rib bone. why. why is it like that.

**Comment by AViewFromTheTop** [comment]
> by the way, have you seen this? https://twitter.com/Cojomax99/status/1493624167907926022/photo/1 i'm pissed off by this. the overlay uses a completely different texture because the different colours on the mouth were not visible on the bedrock screenshots. also look directly under the bottom left rib bone. why. why is it like that. EDIT: here's a brightened version ![image](https://user-images.githubusercontent.com/27739930/154142144-69a31235-f837-4302-98ae-ef13bf130779.png)

yeah I saw, it's strange how they're changing the texture so often when they've had the warden around since 2020, whereas there were like 4 different ore variations and the final ones were decided in a matter of a month or 2

**Comment by MerpisMe** [comment]
> > by the way, have you seen this? https://twitter.com/Cojomax99/status/1493624167907926022/photo/1 i'm pissed off by this. the overlay uses a completely different texture because the different colours on the mouth were not visible on the bedrock screenshots. also look directly under the bottom left rib bone. why. why is it like that. EDIT: here's a brightened version ![image](https://user-images.githubusercontent.com/27739930/154142144-69a31235-f837-4302-98ae-ef13bf130779.png)
> 
> yeah I saw, it's strange how they're changing the texture so often when they've had the warden around since 2020, whereas there were like 4 different ore variations and the final ones were decided in a matter of a month or 2

nah, i dont think they changed the texture here. somehow, brinecraft managed to capture several of these details from just minecraft live 2021, and i didn't realize that they were actually on the official texture. this is definitely a case of the overlay being slightly different from the base texture, i'm certain of it

**Comment by AViewFromTheTop** [comment]
> nah, i dont think they changed the texture here. somehow, brinecraft managed to capture several of these details from just minecraft live 2021, and i didn't realize that they were actually on the official texture so i removed them, thinking they were simply mistakes. this is definitely a case of the overlay being slightly different from the base texture, i'm certain of it

oh
The Warden was barely visible in MC LIVE, so that's quite insane honestly

**Comment by MerpisMe** [comment]
> > nah, i dont think they changed the texture here. somehow, brinecraft managed to capture several of these details from just minecraft live 2021, and i didn't realize that they were actually on the official texture so i removed them, thinking they were simply mistakes. this is definitely a case of the overlay being slightly different from the base texture, i'm certain of it
> 
> oh The Warden was barely visible in MC LIVE, so that's quite insane honestly

yeah im starting to think there's something going on here... he also managed to recreate the new texture based solely on mc live, before we even saw the bedrock screenshots.
![image](https://user-images.githubusercontent.com/27739930/154143543-756e1574-9aee-4b0e-9a27-797118a9d123.png)
the bedrock screenshots were posted on december 9th.

**Comment by AViewFromTheTop** [comment]
> yeah im starting to think there's something going on here... he also managed to recreate the new texture based solely on mc live, before we even saw the bedrock screenshots. ![image](https://user-images.githubusercontent.com/27739930/154143543-756e1574-9aee-4b0e-9a27-797118a9d123.png) the bedrock screenshots were posted on december 9th.

jesus christ

**Comment by MerpisMe** [comment]
> > yeah im starting to think there's something going on here... he also managed to recreate the new texture based solely on mc live, before we even saw the bedrock screenshots. ![image](https://user-images.githubusercontent.com/27739930/154143543-756e1574-9aee-4b0e-9a27-797118a9d123.png) the bedrock screenshots were posted on december 9th.
> 
> jesus christ

i just looked at the actual texture, and...
![image](https://user-images.githubusercontent.com/27739930/154143840-92ddceae-02f1-4be2-b25a-565b1f5cf27b.png)
nevermind. it's quite bad.

**Comment by AViewFromTheTop** [comment]
o

**Comment by AViewFromTheTop** [comment]
> nevermind. it's quite bad.

to be fair, the stream's quality sucked
TERRIBLY

**Comment by MerpisMe** [comment]
> to be fair, the stream's quality sucked TERRIBLY

true, but as is to be expected when you're streaming on youtube

**Comment by MerpisMe** [comment]
pretty one of your latest commits reintroduced the log spamming caused by force loading @AViewFromTheTop

**Comment by AViewFromTheTop** [comment]
> pretty one of your latest commits reintroduced the log spamming caused by force loading @AViewFromTheTop

what's the log saying
It's probably from the Sculk Blob growing, I feared this would happen
AKA, it brings down performance

**Comment by MerpisMe** [comment]
> > pretty one of your latest commits reintroduced the log spamming caused by force loading @AViewFromTheTop
> 
> what's the log saying It's probably from the Sculk Blob growing, I feared this would happen AKA, it brings down performance

yeah. maybe we need to take a different approach to this whole thing. instead of patches would it work if we just make a feature that places a randomly sized and randomly shaped sculk blob that has a catalyst at the center and some sensors and shriekers, and have the biome place the features randomly?
![image](https://user-images.githubusercontent.com/27739930/154146533-cedff133-27d7-4a88-8fb6-9df302596b31.png)

**Comment by MerpisMe** [comment]
> > > pretty one of your latest commits reintroduced the log spamming caused by force loading @AViewFromTheTop
> > 
> > 
> > what's the log saying It's probably from the Sculk Blob growing, I feared this would happen AKA, it brings down performance
> 
> yeah. maybe we need to take a different approach to this whole thing. instead of patches would it work if we just make a feature that places a randomly sized and randomly shaped sculk blob that has a catalyst at the center and some sensors and shriekers, and have the biome place the features randomly? ![image](https://user-images.githubusercontent.com/27739930/154146533-cedff133-27d7-4a88-8fb6-9df302596b31.png)

OH, i actually have an idea! we have a few separate features:
- one with a catalyst and a surrounding blob of sculk
- one that is just a single randomly sized and shaped blob of sculk
- same as previous but with activators
@AlexTheDolphin0 @AViewFromTheTop

**Comment by BluePhoenixLOL** [comment]
> > Unrelated, but I wanted to bring this up. That "portal" in the center of the Deep Dark looks like the Warden kinda, with the tendrils, right?
> > Why does it have The Hollowed's ears instead of the Warden's tendrils?
> 
> Found a screenshot https://i.ytimg.com/vi/XdkNlHrJEoI/maxresdefault.jpg

![image](https://user-images.githubusercontent.com/80720298/154149545-3983deaa-01e3-439b-a78b-6033561c80de.png)
yeah

**Comment by oliviathevampire** [comment]
> > > > pretty one of your latest commits reintroduced the log spamming caused by force loading @AViewFromTheTop
> > > 
> > > 
> > > what's the log saying It's probably from the Sculk Blob growing, I feared this would happen AKA, it brings down performance
> > 
> > 
> > yeah. maybe we need to take a different approach to this whole thing. instead of patches would it work if we just make a feature that places a randomly sized and randomly shaped sculk blob that has a catalyst at the center and some sensors and shriekers, and have the biome place the features randomly? ![image](https://user-images.githubusercontent.com/27739930/154146533-cedff133-27d7-4a88-8fb6-9df302596b31.png)
> 
> OH, i actually have an idea! we could have a few separate features without using any noise: (all references to "blobs" from here onwards refers to generating a blob of blocks using the same method that ores use to generate, for instance)
> 
> * one with a catalyst and a surrounding blob of sculk
> * one that is just a single randomly sized and shaped blob of sculk
> * same as previous but with activators
> * single block of sculk veins in a manner similar to glow lichen
> 
> and then just place all of these completely randomly! @AlexTheDolphin0 @AViewFromTheTop

This would be closer to how bedrock also does it kinda

**Comment by MerpisMe** [comment]
> this is definitely a case of the overlay being slightly different from the base texture, i'm certain of it

well i've figured out why there would be a separate mouth texture for the overlay. it looks SO much better that way.
![2022-02-15_16 30 21](https://user-images.githubusercontent.com/27739930/154161468-3d435940-1c9a-4f48-bec7-be69ed98a01b.png)

**Comment by Soro335** [comment]
@AViewFromTheTop ok, now I've been experimenting with the size of the patches, and I came up with this size, I think it looks better, but...
![image](https://user-images.githubusercontent.com/82042293/154258813-3f45fe67-8078-4fee-8b01-102a3fddd629.png)

**Comment by Soro335** [comment]
But I think we should reduce the radius between catalysts, and add patches like these, is that possible?
![image](https://user-images.githubusercontent.com/82042293/154259040-3c036df5-6fb3-4f8e-bbe0-931ea3732424.png)

**Comment by AViewFromTheTop** [comment]
> > **(all references to "blobs" from here onwards refers to generating a blob of blocks using the same method that ores use to generate, for instance)**
> > 
> > * **one with a catalyst and a surrounding blob of sculk**
> > * **one that is just a single randomly sized and shaped blob of sculk**
> > * **same as previous but with activators**
> > * **single block of sculk veins in a manner similar to glow lichen**
> > 
> > **and then just place all of these completely randomly!**
> 
> would this be viable for that?

In terms of using the method that ores use, absolutely not. It'd be a mess, impossible to place veins, stuff would be hidden in the walls, blobs would be too small. (I'm probably taking it too literally though)

In terms of the different lists of features, that'd definitely work. I'm thinking of doing it like this:
-The BIG Sculk Growths we currently have
-Average Sculk Growths, which can also generate a blob or two around the edge of the main blob
-Random blobs
-Random blobs of veins
-Activators

**Comment by MerpisMe** [comment]
> In terms of using the method that ores use, absolutely not. It'd be a mess, impossible to place veins, stuff would be hidden in the walls, blobs would be too small. (I'm probably taking it too literally though)

yeah, by this i meant just use whatever blob feature we have already that would be suitable for it. scaled down gravel blobs would probably be a better comparison. we'd need to modify it to work such that it only places sculk exposed to air, though. it should also work if we just place veins using an edge detection thing, or just slightly increase the thickness of the blob to place them.

> In terms of the different lists of features, that'd definitely work. I'm thinking of doing it like this:
> -The BIG Sculk Growths we currently have 
> -Average Sculk Growths, which can also generate a blob or two around the edge of the main blob 
> -Random blobs 
> -Random blobs of veins using noise (makes it look natural and more dangerous) 
> -Random blobs of veins (like what we saw at the front of the building where the Warden encounter happened at MC LIVE 2021) 
> -Activators

sure, that probably works better anyway since it allows for much greater variation

**Comment by AViewFromTheTop** [comment]
Also about the current Sculk Growths having "too much Sculk," that's not really true. There was quite literally a MASSIVE wall of Sculk in MC LIVE 2021 next to the building with the Warden, you just have to brighten it to see it. (https://www.youtube.com/watch?v=or1DfXdqu3U at 8:50)
I definetely have to cut down on the wall and especially ceiling Sculk big-time, but there's no shortage of tons of wall sculk in the Deep Dark anyway.

**Comment by AViewFromTheTop** [comment]
> yeah, by this i meant we could just use whatever preexisting blob feature in the game that would be suitable for it. scaled down gravel blobs would probably be a better comparison. we'd need to modify it to work such that it only places sculk exposed to air/cave air, though. it should also work if we just place veins using an edge detection thing, or just slightly increase the thickness of the blob to place them.

At that point we might as well just use SculkGrower's code, which I've already done in the current Sculk feature. I'd just have to copy it and remove all the noise stuff, and add a chance for one or two extra blobs. It's gonna be a lot easier and significantly more efficient to do that as opposed to modifying Ore code just to get the same result
Plus, SculkGrower was designed to place Sculk on floors as MUCH as possible, which is exactly what we need.

**Comment by MerpisMe** [comment]
> At that point we might as well just use SculkGrower's code, which I've already done in the current Sculk feature. I'd just have to copy it and remove all the noise stuff, and add a chance for one or two extra blobs. It's gonna be a lot easier and significantly more efficient to do that as opposed to modifying Ore code just to get the same result Plus, SculkGrower was designed to place Sculk on floors as MUCH as possible, which is exactly what we need- Gravel/Ore patches don't care if they're on ceilings, walls, or floors.

ah! then yeah, go ahead and try that

**Comment by BluePhoenixLOL** [comment]
> > > yeah im starting to think there's something going on here... he also managed to recreate the new texture based solely on mc live, before we even saw the bedrock screenshots. ![image](https://user-images.githubusercontent.com/27739930/154143543-756e1574-9aee-4b0e-9a27-797118a9d123.png) the bedrock screenshots were posted on december 9th.
> > 
> > 
> > jesus christ
> 
> i just looked at the actual texture, and... ![image](https://user-images.githubusercontent.com/27739930/154143840-92ddceae-02f1-4be2-b25a-565b1f5cf27b.png) nevermind. it's quite bad.

update it

**Comment by BluePhoenixLOL** [comment]
we dont have the glow lichen like vein gen, it should only generate 1-2 blocks of sculk veins

**Comment by AViewFromTheTop** [comment]
> we dont have the glow lichen like vein gen, it should only generate 1-2 blocks of sculk veins

That wouldn't make much sense honestly, having a small group of veins matches MC LIVE more and that's what we already have

**Comment by AViewFromTheTop** [comment]
> > we dont have the glow lichen like vein gen, it should only generate 1-2 blocks of sculk veins
> 
> That wouldn't make much sense honestly, having a small group of veins instead of 1 or 2 matches MC LIVE more and that's what we already have

If it needs to be changed though, the radius for them would just have to be shortened and that's it

**Comment by BluePhoenixLOL** [comment]
> > we dont have the glow lichen like vein gen, it should only generate 1-2 blocks of sculk veins
> 
> That wouldn't make much sense honestly, having a small group of veins instead of 1 or 2 matches MC LIVE more and that's what we already have

well we dont see anything like this at minecraft live

BUT we DO see this. 
![image](https://user-images.githubusercontent.com/80720298/154395495-0c401235-9a31-46d4-affb-b75796844305.png)
![image](https://user-images.githubusercontent.com/80720298/154395535-4df82f15-d271-4390-b058-55a99ae0a6f7.png)
![image](https://user-images.githubusercontent.com/80720298/154395636-f662f052-af53-48ab-bab9-b6ecdfb33818.png)

**Comment by BluePhoenixLOL** [comment]
oh, and the secrets of the warden video 
![image](https://user-images.githubusercontent.com/80720298/154395762-05a00b41-b4d4-4726-a26b-3c1d97b71dde.png)
