### ISSUE TITLE
Warden Notes

### ISSUE THREAD

**Issue by AViewFromTheTop** [Osmiooo/wildmod#151]
@AViewFromTheTop 
- [x] Time between detecting vibration and sniffing is actually 100 ticks
- [x] The Warden should immediately pick a wander goal as soon as it finishes emerging, and initiate a sniff as soon as it reaches its wander goal (matches emerge showcase video and MC live 2021)
- [x] The Warden's "sculk dots" (i'll make it a separate overlay) should fade in and out on a constant timer. matches mc live behaviour apparently. let's go, 5 different overlays for the warden!!!! keep the current emissive overlay, we just need to make a new one. the good news is that this one doesn't have to sync with anything at all and can simply run on the world timer

@MerpisMe 
NOTE: These are likely not going to be possible, so this issue can be closed upon confirmation with Merp.
https://www.youtube.com/watch?v=or1DfXdqu3U
- [x] Isolate Warden sound at 8:52
- [x] Isolate different stepping sound that plays at 8:40 and 8:41 (Can also be heard at https://www.youtube.com/watch?v=DWZIfsaIgtE, timestamp 42:43, and at https://www.youtube.com/watch?v=G_xHVgRU1Ho, timestamp 0:19)
- [x] Isolate two other unique idle sounds from https://www.youtube.com/watch?v=DWZIfsaIgtE, also around 8:41
- [x] add this single pixel that i somehow missed aaaaaaaaaaaaaaaaaaaaaaaa
![a](https://user-images.githubusercontent.com/27739930/154350135-a8e7c09c-5dd9-4393-95ec-2fcb43a6a83e.png)

Feel free to add more tasks, remove tasks, and add assignees as needed.

**Comment by MerpisMe** [comment]
> * [ ]  Isolate different stepping sound that plays at 8:40 and 8:41 (Can also be heard at https://www.youtube.com/watch?v=DWZIfsaIgtE, timestamp 42:43)

i can't check for myself, but i'm fairly certain there are only 3 sounds that get pitched differently, since i combed through (i kid you not) every single step sound from both reveals and they all match the three we have right now. it also seems weird for them to only play a total of three times across both reveals if they were in fact their own sound.

**Comment by AViewFromTheTop** [comment]
> sound isolation is an absolute nightmare, in case you can't tell.

i used to do this with songs, i spent hours and could never isolate anything. it frickin sucks, especially WHEN THE BAND REFUSES TO RELEASE THE INSTRUMENTALS OF THEIR B-SIDES FROM 2002. Also quick question, do you think that something along the lines of Spleeter would work at all? Probably not, because that's for music.

**Comment by MerpisMe** [comment]
> Also quick question, do you think that something along the lines of Spleeter would work at all? Probably not, because that's for music.

never heard of it before. does it work well with music?
and even then, regardless of whether it works well with music or not, it'll probably sound really weird because vocals are extremely hard to isolate because we're so used to hearing voices.

**Comment by AViewFromTheTop** [comment]
> the issue with that is that the left and right channel have differing bass and treble levels

what the actual frick is mojang doing lmfao

**Comment by AViewFromTheTop** [comment]
> never heard of it before. does it work well with music? and even then, regardless of whether it works well with music or not, it'll probably sound really weird because vocals are extremely hard to isolate because our brains are trained to recognize voices

ehh... I don't know, but it is indeed isolation. The only issue is that's there's a 99.99% percent it was trained to isolate vocals instead of Warden sounds.

**Comment by MerpisMe** [comment]
> > the issue with that is that the left and right channel have differing bass and treble levels
> 
> what the actual frick is mojang doing lmfao

thats actually not exclusively a minecraft thing, it happens with all games that have stereo audio

**Comment by MerpisMe** [comment]
> > never heard of it before. does it work well with music? and even then, regardless of whether it works well with music or not, it'll probably sound really weird because vocals are extremely hard to isolate because our brains are trained to recognize voices
> 
> ehh... I don't know, but it is indeed isolation. The only issue is that's there's a 99.99% percent it was trained to isolate vocals instead of Warden sounds.

i mean, warden noises are vaguely vocals at best

**Comment by AViewFromTheTop** [comment]
> i mean, warden noises are vaguely vocals at best

"Hey Felix, can you come here for a second?"
"Yeah."
"Hey, could you replicate the sounds of a decaying monster that's made out of squishy, dead flesh stepping on the ground?"
"Yeah. FBVGRYSTFCHBUI."
"Perfect!"

**Comment by MerpisMe** [comment]
> > thats actually not exclusively a minecraft thing, it happens with all games that have stereo audio
> 
> the heck?

it sounds better and it also matches how it works in real life; lower frequencies resonate more in the farther ear because the wavelength is longer, while higher frequencies resonate more in the closer ear because the wavelength is shorter

**Comment by AViewFromTheTop** [comment]
> it sounds better and it also matches how it works in real life; lower frequencies resonate more in the farther ear because the wavelength is longer, while higher frequencies resonate more in the closer ear because the wavelength is shorter

wait do you mean that one channel ALWAYS has higher treble/bass, or it just depends on where the sound's coming from

if it's the second one than I already knew that

**Comment by MerpisMe** [comment]
> > i mean, warden noises are vaguely vocals at best
> 
> "Hey Felix, can you come here for a second?" "Yeah." "Hey, could you replicate the sounds of a decaying monster that's made out of squishy, dead flesh stepping on the ground?" "Yeah. FBVGRYSTFCHBUI." "Perfect!"

sculk has like 14 different break sounds and not one of them match the warden's step sounds when pitched down (i think), it's concerning how many fleshy sounds there are in the game if you think about it

**Comment by MerpisMe** [comment]
> * [ ] The Warden should immediately pick a wander goal as soon as it finishes emerging, and initiate a sniff as soon as it reaches its wander goal (matches emerge showcase video and MC live 2021)

i've added this since its pretty integral to the warden's behaviour. in my video, the warden just stands still after it emerges and only moves once it detects a vibration, which makes the warden seem pretty stupid

**Comment by AViewFromTheTop** [comment]
> i've added this since its pretty integral to the warden's behaviour. in my video, the warden just stands still after it emerges and only moves once it detects a vibration, which makes the warden seem pretty stupid

The huge problem with that is the fact that WanderGoal is gonna start taking over WardenGoal, it really sucks
It WOULD be cool if there was a way to setup a sort movement-priority system though

**Comment by MerpisMe** [comment]
> > i've added this since its pretty integral to the warden's behaviour. in my video, the warden just stands still after it emerges and only moves once it detects a vibration, which makes the warden seem pretty stupid
> 
> The huge problem with that is the fact that WanderGoal is gonna start taking over WardenGoal, it really sucks It WOULD be cool if there was a way to setup a sort movement-priority system though

maybe the core issue is the fact that WanderGoal and WardennGoal are separate classes. what if we tried to merge them?

**Comment by AViewFromTheTop** [comment]
> maybe the core issue is the fact that WanderGoal and WardenGoal are separate classes. what if we tried to merge them?

idk, I'd prefer to make a Movement Priority system honestly. WardenGoal starts, it's set to 2. Once the navigation is idle, it's set to 1. Then WanderGoal can start, at a priority of 1, and once WanderGoal stops, it's set to 0, and the Warden can sniff.

**Comment by AViewFromTheTop** [comment]
> > maybe the core issue is the fact that WanderGoal and WardenGoal are separate classes. what if we tried to merge them?
> 
> idk, I'd prefer to make a Movement Priority system honestly. WardenGoal starts, it's set to 2. Once the navigation is idle, it's set to 1. Then WanderGoal can start, at a priority of 1, and once WanderGoal stops, it's set to 0, and the Warden can sniff.

don't ask why im making it harder to do just trust me itll do the job

**Comment by MerpisMe** [comment]
> idk, I'd prefer to make a Movement Priority system honestly. WardenGoal starts, it's set to 2. Once the navigation is idle, it's set to 1. Then WanderGoal can start, at a priority of 1, and once WanderGoal stops, it's set to 0, and the Warden can sniff.

oh, i didn't realize you were saying it would work, your wording made me think that it wouldn't be possible because of syncing

**Comment by BluePhoenixLOL** [comment]
I Don't think the vibrations travel fast enough, def slower then sculk sensor, can we fix this?

**Comment by MerpisMe** [comment]
> I Don't think the vibrations travel fast enough, def slower then sculk sensor, can we fix this?

this was already fixed, the issue is that the warden is taller and the vibration has to travel slightly further. any faster would mess stuff up

**Comment by AViewFromTheTop** [comment]
> I Don't think the vibrations travel fast enough, def slower then sculk sensor, can we fix this?

it's the same speed, only difference is that the warden can detect farther, and therefore the vibration takes longer to get there

**Comment by AViewFromTheTop** [comment]
> > I Don't think the vibrations travel fast enough, def slower then sculk sensor, can we fix this?
> 
> this was already fixed, the issue is that the warden is taller and the vibration has to travel slightly further. any faster would mess stuff up

i fixed the part where the warden was taller already

**Comment by MerpisMe** [comment]
> > > I Don't think the vibrations travel fast enough, def slower then sculk sensor, can we fix this?
> > 
> > 
> > this was already fixed, the issue is that the warden is taller and the vibration has to travel slightly further. any faster would mess stuff up
> 
> i fixed the part where the warden was taller already

ah

**Comment by AViewFromTheTop** [comment]
btw, we should actually look into this by rebuilding the LIVE 2021 set, specifically the part where he steps on the sensor
We should be able to determine what the proper speed is from that

**Comment by MerpisMe** [comment]
> btw, we should actually look into this by rebuilding the LIVE 2021 set, specifically the part where he steps on the sensor
> We should be able to determine what the proper speed is from that

we have a server set up which has that, you'll have to ask xfrtrex for the ip

**Comment by AViewFromTheTop** [comment]
> we have a server set up which has that, you'll have to ask xfrtrex for the ip

SINCE WHEN

**Comment by AViewFromTheTop** [comment]
@MerpisMe https://www.dropbox.com/s/b4nzhgeh92xtcbe/stepAttempt.mp3?dl=0
Tried to isolate the step, this is the best I could do
There's a frickin heartbeat

**Comment by MerpisMe** [comment]
> @MerpisMe https://www.dropbox.com/s/b4nzhgeh92xtcbe/stepAttempt.mp3?dl=0
> Tried to isolate the step, this is the best I could do
> There's a frickin heartbeat

ezpz

**Comment by MerpisMe** [comment]
> > we have a server set up which has that, you'll have to ask xfrtrex for the ip
> 
> SINCE WHEN

DeepDarkCastle.aternos.me

dont ask about the name, i have no idea why it's called that
xfrtrex will show you where the warden room is

**Comment by MerpisMe** [comment]
> > > we have a server set up which has that, you'll have to ask xfrtrex for the ip
> > 
> > 
> > SINCE WHEN
> 
> DeepDarkCastle.aternos.me
> 
> dont ask about the name, i have no idea why it's called that xfrtrex will show you where the warden room is

wait wait, hang on, he'll have to update the mod

**Comment by AViewFromTheTop** [comment]
Here's my attempt at one of those random sounds, I managed to get rid of the treble/bass thing you were talking about:
https://www.dropbox.com/s/1hc6k5546i7szgd/RandomWarden.mp3?dl=0
Only issue is that I think it has part of a step sound in it, idk

**Comment by AViewFromTheTop** [comment]
> Here's my attempt at one of those random sounds, I managed to get rid of the treble/bass thing you were talking about: https://www.dropbox.com/s/1hc6k5546i7szgd/RandomWarden.mp3?dl=0 Only issue is that I think it has part of a step sound in it, idk

actually i just found the PERFECT amount of fade for it, im gonna add the sound real quick

**Comment by AViewFromTheTop** [comment]
> actually i just found the PERFECT amount of fade for it, im gonna add the sound real quick

nvm, @MerpisMe should I commit it? I think the defaul pitch should be lower, it obviously needs to be edited to sound a bit more like the others, you'd be the best at doing that

**Comment by MerpisMe** [comment]
> > actually i just found the PERFECT amount of fade for it, im gonna add the sound real quick
> 
> nvm, @MerpisMe should I commit it? I think the default pitch should be lower, it obviously needs to be edited to sound a bit more like the others, you'd be the best at doing that

go ahead and commit it, i'll get to it in a bit-- could you remind me in about 3 hours?

**Comment by AViewFromTheTop** [comment]
> go ahead and commit it, i'll get to it in a bit-- could you remind me in about 3 hours?

ok, although idk if i'll be on my pc in 3 hours

**Comment by MerpisMe** [comment]
> * [ ] The Warden's "sculk dots" (i'll make it a separate overlay) should fade in and out on a constant timer. matches mc live behaviour apparently. let's go, 5 different overlays for the warden!!!! keep the current emissive overlay, we just need to make a new one. the good news is that this one doesn't have to sync with anything at all and can simply run on the world timer

@AViewFromTheTop hey you wanna make a new emissive overlay? :trollface: 
jokes aside, this one should be extremely easy to do as stated in the quote above

**Comment by BluePhoenixLOL** [comment]
> - [ ] Isolate two other unique idle sounds from https://www.youtube.com/watch?v=DWZIfsaIgtE, also around 8:41

??? this timestamp is the 1.16 trailer???

**Comment by MerpisMe** [comment]
ok well i've gotta put all sound, texture, model, and animation related stuff on pause until further notice because i won't have access to my pc for who the hell knows how long. i'll only be able to push commits from my phone and work laptop. i'm really glad this is the kind of life i live.

**Comment by AViewFromTheTop** [comment]
why didnt i close this
