### ISSUE TITLE
Copy all code over from experimental snapshot and improve it hahahaha

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#154]
lets gooooooooooooooo

**Comment by MerpisMe** [comment]
so hi all, how does it feel to know that all of our hard work on this mod is for nothing?

**Comment by Soro335** [comment]
our varden is almost similar

**Comment by MerpisMe** [comment]
> our varden is almost similar

actually our warden is technically better, the only difference is the ai, textures, sounds, and animations

**Comment by Soro335** [comment]
ai almost the same, but it not the same

**Comment by MerpisMe** [comment]
thats what i just said

**Comment by MerpisMe** [comment]
> 

yeah i just said that

**Comment by AViewFromTheTop** [comment]
> > our varden is almost similar
> 
> actually our warden is technically better, the only difference is the ai, textures, sounds, and animations

It is actually better, which is surprising. Mojang used all their complex stuff, our Warden works with just a few classes, just as good. Obviously they're not releasing the most up-to-date Warden though. When they decide to do that, we're screwed.
