### ISSUE TITLE
Sculk Blocks and darkness notes

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#156]
Sculk Catalyst:
- [ ] Only one catalyst can work in a radius of 8 blocks
- [ ] Reacts to the death of mobs only within a radius of 8 blocks
- [ ] Spread sculks as in the official version

Sculk Shrieker:
- [ ] Does not give the player the darkness effect
- [ ] Is not activated by bats activating sensors
- [ ] Only one shrieker can work within a 16 block radius
- [ ] Has a 5 second cooldown

Darkness Effect:
- [ ] Gives world fog first, then gives fullydark fog
- [ ] The fog is much closer to the player

**Comment by BluePhoenixLOL** [comment]
> - [ ] Does not conflict with night vision

Wrong.

**Comment by MerpisMe** [comment]
We should hold off on all of the darkness stuff since it's very obvious that the darkness we got in 1.19_exp_1 is unfinished. They very clearly intend for the fog to pulse in and out, since that's how it acted in MC live 2021 (and it just looks better)
