### ISSUE TITLE
Incompatible with Ost Overhaul

### ISSUE THREAD

**Issue by Treetrain1** [Osmiooo/wildmod#158]
When you launch the game with TWM and Ost Overhaul installed, it crashes because it registers the music under two different ids. 

The only workaround is to manually remove the music from the ost-overhaul.json config file every time you want to launch minecraft
I think it is because of the way sounds are registered

Affects Beta 0.6

latest.log
https://pastebin.com/raw/hbTEWMKJ

Crash Report
https://pastebin.com/raw/xgXJ9gY0

![image](https://user-images.githubusercontent.com/39657565/155023462-ca79a350-e2ad-41ac-bf82-6e1842a4e6ce.png)

**Comment by Toilet-Man** [comment]
Also I wanna say thank you for the issue you submitted or else I would've just kept v0.4 and left it at that
