### ISSUE TITLE
Implement Mojang's Keyframe System

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#160]
...and copy the Warden animations over.

**Comment by AViewFromTheTop** [comment]
how is that even possible
mojang took what is quite possibly the worst and most unreadable approach to keyframes possible to all humankind

**Comment by MerpisMe** [comment]
> how is that even possible
> mojang took what is quite possibly the worst and most unreadable approach to keyframes possible to all humankind

i know

the "easier" solution would be implementing catmull clark-type easing (smooth type keyframe in blockbench) to the current animation API, since all of the warden's animations use it @LIUKRAST 
it'd also eliminate any need for ease ins or ease outs, and even completely eliminate back in and out. i just have no idea how it works.

**Comment by AViewFromTheTop** [comment]
i tried to start on this yesterday, and long-story short, it is NOT worth it when AnimationAPI's right there
hopefully someday blockbench will add support for 1.19 keyframe stuff, but even then there needs to be much better documentation on how to use it first

**Comment by MerpisMe** [comment]
> i tried to start on this yesterday, and long-story short, it is NOT worth it when AnimationAPI's right there
> hopefully someday blockbench will add support for 1.19 keyframe stuff, but even then there needs to be much better documentation on how to use it first

1.19 keyframe stuff is identical to bedrock's animation system, it just doesn't have a molang parser

**Comment by AViewFromTheTop** [comment]
> 1.19 keyframe stuff is identical to bedrock's animation system, it just doesn't have a molang parser

what's a molang parser
is that the .json animation stuff?
If so, I think GeckoLib might actually become good in 1.19, i'm sure they'd find out a way to use it

**Comment by MerpisMe** [comment]
> what's a molang parser 
> is that the .json animation stuff? 

yeah, animations in bedrock use molang

> If so, I think GeckoLib might actually become good in 1.19, i'm sure they'd find out a way to use it

...oh boy

**Comment by AViewFromTheTop** [comment]
> ...oh boy

Assuming they actually let you use idle and walk animations lmfao

**Comment by BluePhoenixLOL** [comment]
> > ...oh boy
> 
> Assuming they actually let you use idle and walk animations lmfao
> 
> Which will never happen

suprise! frog animations

**Comment by MerpisMe** [comment]
> > > ...oh boy
> > 
> > 
> > Assuming they actually let you use idle and walk animations lmfao
> > Which will never happen
> 
> suprise! frog animations

that still wont help us for shit lol
