### ISSUE TITLE
Warden sounds do not become quieter based on distance

### ISSUE THREAD

**Issue by Skeithh** [Osmiooo/wildmod#164]
Being able to hear wardens as if they're directly next to you from over 50 blocks away feels a bit... wrong? I have a warden trapped quite some blocks underground and I can still hear it clear as day when I'm all the way on the surface. If they wouldn't be as loud as standing next to them it wouldn't be an issue but it is quite noisy.

This is on TWM version beta 0.6

**Comment by Treetrain1** [comment]
I believe they did this to match the experimental snapshot, but I do agree that it feels weird.

**Comment by MerpisMe** [comment]
> I believe they did this to match the experimental snapshot, but I do agree that it feels weird.

^

i don't like it either, but it's done for parity. if we change it we'll get people complaining about the contrary
