### ISSUE TITLE
New Mob - Allay isn't stable or normal

### ISSUE THREAD

**Issue by arichorn** [Osmiooo/wildmod#168]
The Allay has a lot of problems in this latest commit, I did some testing and noticed a lot of problems
Allay Spawn Egg (the name isn't right)
Allay randomly flys to the sky and doesn't come to you
giving Allay a cookie or anything doesn't do nothing, just flys in the sky as usual
the Allay has problems rotating when moving around.
Allay's Textures are alright but does need a better design.

Hope you see this!

**Comment by Soro335** [comment]
We know about this! allay is ported from twm+ mod and therefore has no official functions and texture, this will be fixed soon

**Comment by arichorn** [comment]
thanks and looking forward for 1.18.2 versions! this allay will be fun!
