### ISSUE TITLE
1.18.2 Support issues

### ISSUE THREAD

**Issue by arichorn** [Osmiooo/wildmod#170]
I have known errors with the wild mod lately, I forked this and tried my best to make it support 1.18.2, ever since 1.18.2 released I noticed a code change in TheAccurateSculk folder, I have a check mark list below me and a .txt of the errors I witnessed after making it support 1.18.2.
[TWM-ERRORS.txt](https://github.com/Osmiooo/wildmod/files/8257583/TWM-ERRORS.txt)

and if I can't do it then I'm the worst coder there is.

Fixing the VanillaBiomeParametersMixin Issues

blocks\mangrove\MangroveWood (Fabric API tool attribute) 

Fixing the "fromAccurateSculk" Coding

**Comment by Treetrain1** [comment]
Hey, I am also trying to port the mod to 1.18.2 in #166
Do you know of a way to fix the issues with the `configure()` and `withPlacement()` methods in RegisterWorldgen.java?
Mojang removed these methods in 1.18.2 and a workaround is needed.

**Comment by Treetrain1** [comment]
nevermind found a fix

**Comment by arichorn** [comment]
oh alright

**Comment by AViewFromTheTop** [comment]
> I have known errors with the wild mod lately, I forked this and tried my best to make it support 1.18.2, ever since 1.18.2 released I noticed a code change in TheAccurateSculk folder, I have a check mark list below me and a .txt of the errors I witnessed after making it support 1.18.2. [TWM-ERRORS.txt](https://github.com/Osmiooo/wildmod/files/8257583/TWM-ERRORS.txt)
> 
> and if I can't do it then I'm the worst coder there is.
> 
> Fixing the VanillaBiomeParametersMixin Issues
> 
> blocks\mangrove\MangroveWood (Fabric API tool attribute)
> 
> Fixing the "fromAccurateSculk" Coding

That's already fixed in a separate Pull Request.
