### ISSUE TITLE
Mangrove Wasteland?! (Terrain Issue for Mangrove Swamp)

### ISSUE THREAD

**Issue by arichorn** [Osmiooo/wildmod#173]
![2022-03-20_15 40 15](https://user-images.githubusercontent.com/78001398/159185125-e2cabc54-f87b-4dd8-84a9-8158a06d2cdc.png)
this is now a mangrove wasteland, wtf happened to the swamp

**Comment by arichorn** [comment]
this is from the latest commit when the new mangrove wood textures were added

**Comment by Osmiooo** [comment]
We know, and we're trying to fix this asap.

**Comment by Gamerdacchund99** [comment]
no trees, no lakes...

JUST A EMPTY WASTELAND!!

**Comment by Osmiooo** [comment]
> this is from the latest commit when the new mangrove wood textures were added (also, you forgot to modify the texture to the mangrove chest boat)

Good to know

**Comment by BluePhoenixLOL** [comment]
i fix
