### ISSUE TITLE
22w12a To-Do List (Unoffical)

### ISSUE THREAD

**Issue by arichorn** [Osmiooo/wildmod#175]
Boats With Chests 

New Sculk Shrieker Changes

Swift Sneak Enchantment

------------------------**CHANGES IN 22W12A**-----------------------
The Deep Dark biome is now less flooded than surrounding areas
Leaves are now waterloggable
Removed debug hotkey cycling render distance
---------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/78001398/160012200-7f6dc2aa-8bda-4c46-8807-e9e5f17179b4.jpg)

**Comment by Soro335** [comment]
We are aware of all changes.  Stop making issues with changes that are not yet in mod, we follow the snapshots and know everything. Thank u

**Comment by arichorn** [comment]
oh, I tried to remind y'all early as possible because (I actually don't know why so I'll give a random reason?) confidence?

**Comment by BluePhoenixLOL** [comment]
> oh, I tried to remind y'all early as possible because (I actually don't know why so I'll give a random reason?) confidence?

yeah, appreciate the thought but we know about the snapshots, and we do many tests and stuff with them when they come out.
