### ISSUE TITLE
Unable to fly in Creative.

### ISSUE THREAD

**Issue by HellishINC** [Osmiooo/wildmod#185]
Fabric Loader: 0.14.8
Fabric API: 0.56.0 and current local git build
Mod: "[0.7_DEV+MC_1.18.2-unstable](https://github.com/Osmiooo/wildmod/actions/runs/2471687138)"

When using this build of twm, players are unable to double tap jump to fly in creative mode.

No relevant errors are in the log but here they are for completeness sake: https://mclo.gs/UjlcwFv

**Comment by armuell** [comment]
yea I'm experiencing this as well, do you know the latest build where this doesn't happen?

**Comment by HellishINC** [comment]
I built the latest commit. The current public build does not work for 1.18.2.

**Comment by armuell** [comment]
Yea I used the same commit you did, I was just curious if there were any previous commits you might have tried that didn't disable flying. This bug occurs when trying to fly in creative and when trying to use elytra in survival which is unfortunate

**Comment by jeedrb** [comment]
Having the same issue with the latest build.
