### ISSUE TITLE
Mangrove swamp generation with Terralith

### ISSUE THREAD

**Issue by Treetrain1** [Osmiooo/wildmod#21]
It would be nice if the mangrove swamps were able to generate while using Terralith.

I don't know if this is possible, but I would like to have mangrove swamps in my Terralith worlds.

**Comment by Soro335** [comment]
We cannot add support for Terralith because this is not a problem from our side, but from the side of Terralith developers.
Please ask Terralith developers for support for other generation mods.

**Comment by BluePhoenixLOL** [comment]
> We cannot add support for Terralith because this is not a problem from our side, but from the side of Terralith developers. Please ask Terralith developers for support for other generation mods.

well no
