### ISSUE TITLE
Warden heartbeat & anger system

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#23]
The gist of it would be as follows:
- by default, the warden's chest beats once every 2-3 seconds (sounds provided as entity.warden.heartbeat)
- as its suspicion increases, this interval decreases
- the warden becomes "angry" when its suspicion surpasses a certain level, and it cues the roar sound effect
- tie the warden's speed to its suspicion level
- optionally, if you know how to, make the chest overlay pulse in time with the heartbeats
- also optionally, if you know how to, make the tendrils glow whenever the warden receives a vibration (warden_tendrils.png)

**Comment by AViewFromTheTop** [comment]
I think I should be able to do that aside from the chest overlay pulsing. There are two problems though:
1. What level, exactly, does the Warden target the player at? 3 or 5?
2. What should the max speed for the Warden be? I’ve tested increasing its speed alongside suspicion and it’s easy, but if it goes too fast it’s not a threat anymore.

**Comment by AViewFromTheTop** [comment]
> The gist of it would be as follows:
> 
> * by default, the warden's chest beats once every 2-3 seconds (sounds provided as entity.warden.heartbeat)
> * as its suspicion increases, this interval decreases
> * the warden becomes "angry" when its suspicion surpasses a certain level, and it cues the roar sound effect
> * tie the warden's speed to its suspicion level
> * optionally, if you know how to, make the chest overlay pulse in time with the heartbeats
> * also optionally, if you know how to, make the tendrils glow whenever the warden receives a vibration (warden_tendrils.png)

Quick question, what is the heartbeat registered as in RegisterSounds? I don't see a heartbeat mentioned anywhere.

**Comment by BluePhoenixLOL** [comment]
> I think I should be able to do that aside from the chest overlay pulsing and tendril glowing. There are two problems though:
> 
> 1. What level, exactly, does the Warden roar at the player at? 3 or 5?
> 2. What should the max speed for the Warden be? I’ve tested increasing its speed alongside suspicion and it’s easy, but if it goes too fast it’s not a threat anymore.
>    If the max speed is just enough for a sprinting player to outrun it, I’ve already got the answer.

i think it depends if the vibration comes from the player

**Comment by MerpisMe** [comment]
> 

1. 3. Basically, we want the vibrations to work similar to sculk frequency, where different types of vibrations increase the suspicion level by different amounts, with player interactions being the strongest.
2. Max speed should probably be the same as the player's max speed (around 0.7 i think?), but only do this if it's angry.

**Comment by AViewFromTheTop** [comment]
> > 
> 
> 1. 5; Basically, we want the vibrations to work similar to sculk frequency, where different types of vibrations increase the suspicion level by different amounts, with player interactions being the strongest.
> 2. Max speed should probably be the same as the player's max speed (around 0.7 i think?), but only do this if it's angry.

As of now I have the Warden's speed maxing out at 1.15, which is enough for a sprinting player to escape but still feel threatened.
Also since I'm just seeing this I'll have to redo some of the new suspicion stuff I added. I'm guessing I should make the value for the Warden to target something be 15, with player vibrations being worth 3. I'll also have to change the listen method and SimpleGameEventDispatcher a bit, but it should all work.

**Comment by MerpisMe** [comment]
alright! you up for implementing sniffing when you're finishing ironing all of this out? reminder that sniffing should cause the warden to stop moving, play a sniff sound, and then move.

**Comment by AViewFromTheTop** [comment]
> alright! you up for implementing sniffing when you're finishing ironing all of this out? reminder that sniffing should cause the warden to stop moving, play a sniff sound, and then move.

I'm honestly not too sure, I'm really not that good at entity movement an AI stuff. I'm best at adding to something that already exists honestly.
If I try making the Warden sniff, it'll probably just stay on my PC for a bit while I figure things out. Chances are, once I've fixed some things, I'd start on it. I can't guarantee I'll be able to do it, though.

**Comment by MerpisMe** [comment]
that's fine, just wanted to pitch the idea to you to see if you'd know how to approach it. as a side question, could you make digging get called on by a global variable so that we can implement a temporary digging animation? (just sliding into the ground for now) we currently don't have any way to know when the warden is digging from the entity model file

**Comment by AViewFromTheTop** [comment]
> that's fine, just wanted to pitch the idea to you to see if you'd know how to approach it. as a side question, could you make digging get called on by a global variable so that we can implement a temporary digging animation? (just sliding into the ground for now) we currently don't have any way to know when the warden is digging from the entity model file

emergeTicksLeft>0 && hasEmerged==true
Unless I'm misunderstanding what a global variable is, that should be the answer
Also, I think we should get Sculk Sensor communication with the Warden done before sniffing

**Comment by AViewFromTheTop** [comment]
> alright! you up for implementing sniffing when you're finishing ironing all of this out? reminder that sniffing should cause the warden to stop moving, play a sniff sound, and then move.

Quess what's in my newest pull request!
