### ISSUE TITLE
Warden's vibration system is slightly broken

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#3]
The Warden mob seems to be a bit broken at the moment, and when it detects multiple vibrations in rapid succession it sprints incredibly quickly towards said vibrations.

**Comment by BluePhoenixLOL** [comment]
Thanks, we will look into it :)

**Comment by LIUKRAST** [comment]
Thanks for reporting, Warden is very complex and i need a lot of feedback to make it work as good as possible. Ill improve it in the next version.

**Comment by AViewFromTheTop** [comment]
idk why anything with a # automatically links to an issue, didn't know about then when pasting the logs for the other report- sorry about that.
Also, has this issue been resolved? I little while ago a stopped Wardens from emitting GameEvents, and before then I put in a check to stop vibration spamming. More recently when I was working on WardenGoal.java with entity suspicion, the fast following should also be fixed (unless, of course, the Warden is highly suspicious of the entity it's following)

**Comment by BluePhoenixLOL** [comment]
seems fine now

**Comment by AViewFromTheTop** [comment]
first(?) maple interaction pogger
