### ISSUE TITLE
Warden runs away from the player when warden takes damage and gets stuck

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#33]
https://user-images.githubusercontent.com/82042293/149581434-5f0d2cb1-ebc2-41f4-a89d-76ae3a61dbe7.mp4

https://user-images.githubusercontent.com/82042293/149581469-01c463dc-77a8-47e2-b0ae-5cab83065016.mp4

**Comment by AViewFromTheTop** [comment]
Idk why it always automatically closes the issue when it's mentioned in a commit
Either way, is this fixed? (Of course once it builds with the latest commit)

**Comment by Soro335** [comment]
fixed
