### ISSUE TITLE
Server stops in startup (Couldn't load tag)

### ISSUE THREAD

**Issue by Toilet-Man** [Osmiooo/wildmod#39]
I previously installed the mod and was working fine. Played for a while then restarted my server then it gives me this error and it prevents the server from loading completely

> [18:04:12] [Worker-Main-5/ERROR]: Couldn't load tag minecraft:clicking as it is missing following references: minecraft:click (from The Wild Mod)

Idk what could be causing this

Here's the log file:
[latest.log](https://github.com/Osmiooo/wildmod/files/7873723/latest.log)

**Comment by AViewFromTheTop** [comment]
That's fixed in the next update. Thank you for reporting the bug, though!

**Comment by Toilet-Man** [comment]
when is the last update?

**Comment by Toilet-Man** [comment]
can you give me the new "clicking.json" if that was the only thing to change?

**Comment by AViewFromTheTop** [comment]
> when is the last update?

I don't know when exactly it'll be, but you can always download the latest artifacts from GitHub to get the most up-to-date version of the mod.
Click "Artifacts" here, and you should get a download:
https://github.com/Osmiooo/wildmod/actions/runs/1699972239

**Comment by Toilet-Man** [comment]
Thanks a lot <3

**Comment by AViewFromTheTop** [comment]
> Thanks a lot <3

You're welcome, and I hope you have fun!
