### ISSUE TITLE
[Bug] Warden detects jumping sound whilst player is crouching

### ISSUE THREAD

**Issue by Treetrain1** [Osmiooo/wildmod#4]
Here's a video explaining the bug: https://user-images.githubusercontent.com/39657565/145697500-b0a2bc8c-8ccd-411c-b6a8-dafc6f8bfaa0.mp4

 I am using Fabric Loader 0.12.11 and Fabric API 44.0

I believe this affects every version of the mod, but I am using Beta 0.3 in the video.

Game Version: 1.18.1 (I don't know if this helps)

**Comment by LIUKRAST** [comment]
Thanks for reporting! Ill fix as soon as possible!

**Comment by LIUKRAST** [comment]
Fixed! Ill upload a new Mod version soon!
