### ISSUE TITLE
Sculk Shriekers do not have a cooldown

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#40]
Sculk shriekers do not have a cooldown when being stood upon, causing them to continuously shriek. They _probably_ should only activate one time when stood on. Same goes for sculk sensors.

**Comment by AViewFromTheTop** [comment]
Shouldn't they be that way though? Pressure plates act this way, and I don't think that stepping on Sculk would make it any less agitated than a vibration

**Comment by MerpisMe** [comment]
True, but the issue is that it continues to vibrate even if the player doesn't move. I think at the very least it probably should have a cooldown between detections at the very least, it feels a bit buggy right now

**Comment by AViewFromTheTop** [comment]
> True, but the issue is that it continues to activate even if the player doesn't move. I think at the very least it probably should have a cooldown between detections at the very least, it feels a bit buggy right now

I won't be able to do this with Sensors, but I should be able to do this with Shriekers.
