### ISSUE TITLE
When a frog eats a magma cube/slime near a sculk catalyst, sculk is spawning

### ISSUE THREAD

**Issue by Osmiooo** [Osmiooo/wildmod#41]
It doesn't work like that in bedrock, the magma cube/slime should not be /kill, it should be kicked out of the world

**Comment by BluePhoenixLOL** [comment]
I believe this is just a bug on bedrock

**Comment by BluePhoenixLOL** [comment]
I belive this is a bedrock bug, but just incase its not i will keep it open

**Comment by AViewFromTheTop** [comment]
> I belive this is a bedrock bug, but just incase its not i will keep it open

The fix will need yet again more timers, but there is indeed a fix for it.
1. New timer to decide when to kick the entity
2. Set target entity to invulnerable
3. NBT to remember which entity it grabbed to prevent invulnerable slimes when logging out and back in
4. Kick entity
5. More code to drop the items properly

**Comment by BluePhoenixLOL** [comment]
but why, when you get eaten you die, right?

**Comment by AViewFromTheTop** [comment]
> but why, when you get eaten you die, right?

It does actually make sense though, the Sculk can't spread inside a frog without the frog dying too
