### ISSUE TITLE
Mud block does not turn into clay if there is more than one dripstone

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#46]
![image](https://user-images.githubusercontent.com/82042293/149643241-a6975ce4-ad1a-4035-bb5e-8d933a0854d6.png)

**Comment by MerpisMe** [comment]
https://user-images.githubusercontent.com/27739930/150694298-dcdffac0-e013-4fd1-98a0-de63f3d79fb1.mp4

**Comment by MerpisMe** [comment]
Fixed in commit ffebf5a
