### ISSUE TITLE
Mangrove Propagule Properties Are Being Compared With Water

### ISSUE THREAD

**Issue by JustFoxx** [Osmiooo/wildmod#47]
When i was trying to craft a crafting, "server" (i was playing on singleplayer) just crashed and i got that error
[crash-2022-01-16_10.44.59-server.txt](https://github.com/Osmiooo/wildmod/files/7876674/crash-2022-01-16_10.44.59-server.txt)
[latest.log](https://github.com/Osmiooo/wildmod/files/7876675/latest.log)

**Comment by BluePhoenixLOL** [comment]
hmm

**Comment by BluePhoenixLOL** [comment]
one of your mods may be causing it, but we will look into it

**Comment by BluePhoenixLOL** [comment]
@MerpisMe invalid? so should i just close it, or?

**Comment by JustFoxx** [comment]
sorry for trouble
https://github.com/kvverti/colormatic/issues/74

**Comment by JustFoxx** [comment]
i have got same error and i know that there is error about mangrovepropagule that its crashing about it doesnt suppose it to be her
[crash-2022-01-20_14.47.42-server.txt](https://github.com/Osmiooo/wildmod/files/7905692/crash-2022-01-20_14.47.42-server.txt)
e

**Comment by MerpisMe** [comment]
> i have got same error and i know that there is error about mangrovepropagule that its crashing about it doesnt suppose it to be her
> [crash-2022-01-20_14.47.42-server.txt](https://github.com/Osmiooo/wildmod/files/7905692/crash-2022-01-20_14.47.42-server.txt)
> e

hmmm, that's really strange. we'll have a look again

**Comment by AViewFromTheTop** [comment]
I experienced this bug with Accurate Sculk a while ago, essentially it's trying to get non-existent properties from a block.
In this case it seems to be trying to get the "hanging" property from Water instead of Propagules.

**Comment by AViewFromTheTop** [comment]
WHY DOES GITHUB ALWAYS AUTOMATICALLY CLOSE ISSUES WHEN THEYRE MENTIONED IN A COMMIT
Either way, once the new build is finished, would someone be able to test it? I made a single-biome world of just Mangrove Swamps, and I didn't have this issue even with a randomTickSpeed of 999.

**Comment by JustFoxx** [comment]
*waits for update that repairs that error*

**Comment by MerpisMe** [comment]
> waits for update that repairs that error

it'll be a while. we won't be releasing any bugfixes for 0.5 unless we find one that is absolutely crucial to find a resolution for

**Comment by JustFoxx** [comment]
how the hell that thing isnt crucial, its like sometimes making game literally unplayable becuz always when u join world it automatically crashes

**Comment by MerpisMe** [comment]
> how the hell that thing isnt crucial, its like sometimes making game literally unplayable becuz always when u join world it automatically crashes

because you're currently the only one experiencing it. if you want a version where this is fixed, go to the Actions tab, click on the name of the latest commit with a green check mark, and download the Artifacts.zip file. The correct file will be the one without "sources" "dev" or "dev-sources"

**Comment by marewey** [comment]
I am experiencing it too. It seems to be a new gen of the mangrove biome. It seems to be the MangrovePropagule


    >Description: Ticking entity

   >java.lang.IllegalArgumentException: Cannot get property class_2746{name=hanging, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
    at net.minecraft.class_2688.method_11654(class_2688.java:98)
    at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.attachedDirection(MangrovePropagule.java:49)
    at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.method_9558(MangrovePropagule.java:76)
    at net.minecraft.class_1542.handler$coa007$tick(class_1542.java:4075)
    at net.minecraft.class_1542.method_5773(class_1542.java:99)
    at net.minecraft.class_3218.method_18762(class_3218.java:699)
    at net.minecraft.class_1937.method_18472(class_1937.java:487)
    at net.minecraft.class_3218.method_31420(class_3218.java:360)
    at net.minecraft.class_5574.method_31791(class_5574.java:54)
    at net.minecraft.class_3218.method_18765(class_3218.java:328)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
    at net.minecraft.class_3176.method_3813(class_3176.java:324)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
    at java.base/java.lang.Thread.run(Thread.java:833)

   >A detailed walkthrough of the error, its code path and all known details is as follows:

   >-- Head --
    Thread: Server thread
    Stacktrace:
    at net.minecraft.class_2688.method_11654(class_2688.java:98)
    at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.attachedDirection(MangrovePropagule.java:49)
    at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.method_9558(MangrovePropagule.java:76)
    at net.minecraft.class_1542.handler$coa007$tick(class_1542.java:4075)
    at net.minecraft.class_1542.method_5773(class_1542.java:99)
    at net.minecraft.class_3218.method_18762(class_3218.java:699)
    at net.minecraft.class_1937.method_18472(class_1937.java:487)
    at net.minecraft.class_3218.method_31420(class_3218.java:360)
    at net.minecraft.class_5574.method_31791(class_5574.java:54)
    at net.minecraft.class_3218.method_18765(class_3218.java:328)

  >-- Entity being ticked --
    Details:
    Entity Type: minecraft:item (net.minecraft.class_1542)
    Entity ID: 394
    Entity Name: block.twm.mangrove_propagule
    Entity's Exact location: -774.36, 75.00, 2942.88
    Entity's Block location: World: (-775,75,2942), Section: (at 9,11,14 in -49,4,183; chunk contains blocks -784,-64,2928 to -769,319,2943), Region: (-2,5; contains chunks -64,160 to -33,191, blocks -1024,-64,2560 to -513,319,3071)
    Entity's Momentum: 0.00, -0.12, 0.00
    Entity's Passengers: []
    Entity's Vehicle: null

**Comment by MerpisMe** [comment]
> I am experiencing it too. It seems to be a new gen of the mangrove biome. It seems to be the MangrovePropagule
> 
> ```
> >Description: Ticking entity
> ```
> 
> > java.lang.IllegalArgumentException: Cannot get property class_2746{name=hanging, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
> > at net.minecraft.class_2688.method_11654(class_2688.java:98)
> > at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.attachedDirection(MangrovePropagule.java:49)
> > at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.method_9558(MangrovePropagule.java:76)
> > at net.minecraft.class_1542.handler$coa007$tick(class_1542.java:4075)
> > at net.minecraft.class_1542.method_5773(class_1542.java:99)
> > at net.minecraft.class_3218.method_18762(class_3218.java:699)
> > at net.minecraft.class_1937.method_18472(class_1937.java:487)
> > at net.minecraft.class_3218.method_31420(class_3218.java:360)
> > at net.minecraft.class_5574.method_31791(class_5574.java:54)
> > at net.minecraft.class_3218.method_18765(class_3218.java:328)
> > at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
> > at net.minecraft.class_3176.method_3813(class_3176.java:324)
> > at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
> > at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
> > at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
> > at java.base/java.lang.Thread.run(Thread.java:833)
> 
> > A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> > -- Head --
> > Thread: Server thread
> > Stacktrace:
> > at net.minecraft.class_2688.method_11654(class_2688.java:98)
> > at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.attachedDirection(MangrovePropagule.java:49)
> > at frozenblock.wild.mod.blocks.mangrove.MangrovePropagule.method_9558(MangrovePropagule.java:76)
> > at net.minecraft.class_1542.handler$coa007$tick(class_1542.java:4075)
> > at net.minecraft.class_1542.method_5773(class_1542.java:99)
> > at net.minecraft.class_3218.method_18762(class_3218.java:699)
> > at net.minecraft.class_1937.method_18472(class_1937.java:487)
> > at net.minecraft.class_3218.method_31420(class_3218.java:360)
> > at net.minecraft.class_5574.method_31791(class_5574.java:54)
> > at net.minecraft.class_3218.method_18765(class_3218.java:328)
> 
> > -- Entity being ticked --
> > Details:
> > Entity Type: minecraft:item (net.minecraft.class_1542)
> > Entity ID: 394
> > Entity Name: block.twm.mangrove_propagule
> > Entity's Exact location: -774.36, 75.00, 2942.88
> > Entity's Block location: World: (-775,75,2942), Section: (at 9,11,14 in -49,4,183; chunk contains blocks -784,-64,2928 to -769,319,2943), Region: (-2,5; contains chunks -64,160 to -33,191, blocks -1024,-64,2560 to -513,319,3071)
> > Entity's Momentum: 0.00, -0.12, 0.00
> > Entity's Passengers: []
> > Entity's Vehicle: null

hmm. @AViewFromTheTop

**Comment by marewey** [comment]
> > how the hell that thing isnt crucial, its like sometimes making game literally unplayable becuz always when u join world it automatically crashes
> 
> because you're currently the only one experiencing it. if you want a version where this is fixed, go to the Actions tab, click on the name of the latest commit with a green check mark, and download the Artifacts.zip file. The correct file will be the one without "sources" "dev" or "dev-sources"

This seems to have resolved the issue.

**Comment by MerpisMe** [comment]
> > > how the hell that thing isnt crucial, its like sometimes making game literally unplayable becuz always when u join world it automatically crashes
> > 
> > 
> > because you're currently the only one experiencing it. if you want a version where this is fixed, go to the Actions tab, click on the name of the latest commit with a green check mark, and download the Artifacts.zip file. The correct file will be the one without "sources" "dev" or "dev-sources"
> 
> This seems to have resolved the issue.

oh, glad to hear it!

**Comment by marewey** [comment]
Nevermind. A new error popped up. but let me double check that wasnt another mod tho. lol
