### ISSUE TITLE
Delay Warden Vibration based on Distance

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#49]
(Based on a suggestion in our discord) Make the Warden only react to the vibration when the particle reaches its head rather than reacting immediately once the vibration is made. This _should_ be a trivial thing to implement, if I'm not wrong; take the distance of the vibration, wait the same amount of time it would take for the particle to reach the Warden's head, (or estimate it if there's a delay between the particle's movement ticks) and _then_ have it react. I'd suggest checking the sculk sensor code as a reference if you're not sure as to how to go about this.

**Comment by AViewFromTheTop** [comment]
> (Based on a suggestion in our discord) Make the Warden only react to the vibration when the particle reaches its head rather than reacting immediately once the vibration is made. This _should_ be a trivial thing to implement, if I'm not wrong; take the distance of the vibration, wait the same amount of time it would take for the particle to reach the Warden's head, (or estimate it if there's a delay between the particle's movement ticks) and _then_ have it react. I'd suggest checking the sculk sensor code as a reference if you're not sure as to how to go about this.

it's not easy, read comments on my latest commit
