### ISSUE TITLE
When activated, the Warden will go to the spot the players is, instead of setting its Target Goal to the player.

### ISSUE THREAD

**Issue by BluePhoenixLOL** [Osmiooo/wildmod#5]
upon being activated by walking, jumping etc, the Warden will go to the area the players is, instead of setting its Target Goal to the player. this means it will go too the spot you are, but you can avoid being killed by sneaking and moving away from the block you were a second ago.

**Comment by AlexTheDolphin0** [comment]
I feel like thats good because it hears vibrations right? so maybe make it update where its target is if it hears any more movement.

**Comment by BluePhoenixLOL** [comment]
> I feel like thats good because it hears vibrations right? so maybe make it update where its target is if it hears any more movement.

no, as it doesnt attack the player most of the time

**Comment by BluePhoenixLOL** [comment]
look at minecraft live, when he hears the player directly, it gets mad and roars, then charges to the player with the player as its target

**Comment by AViewFromTheTop** [comment]
> look at minecraft live, when he hears the player directly, it gets mad and roars, then charges to the player with the player as its target

Would this be considered fixed by my latest commits?
