### ISSUE TITLE
Colliding entity with block crash

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#51]
I'm assuming this crash is caused by the whole "stepping on sculk sensors activates them" thing
[crash-2022-01-17_11.36.22-server.txt](https://github.com/Osmiooo/wildmod/files/7883620/crash-2022-01-17_11.36.22-server.txt)

**Comment by AViewFromTheTop** [comment]
When exactly was the build you used from? I fixed an extremely similar bug yesterday. If it's from a newer build, I don't know what exactly would be causing this, as the only cause for this was fixed.

**Comment by MerpisMe** [comment]
> 

This was from a user on our discord server, so it's possible they were using a broken preview version. 
![image](https://user-images.githubusercontent.com/27739930/149811886-dfa66c37-7017-490d-8b69-ba235903ee48.png)

**Comment by AViewFromTheTop** [comment]
> > 
> 
> This was from a user on our discord server, so it's possible they were using a broken preview version. ![image](https://user-images.githubusercontent.com/27739930/149811886-dfa66c37-7017-490d-8b69-ba235903ee48.png)

Nope. That was fixed yesterday, I had the exact same crash. I put in a check to see if it was a LivingEntity yesterday, so this doesn't happen anymore.

**Comment by AViewFromTheTop** [comment]
> > > 
> > 
> > 
> > This was from a user on our discord server, so it's possible they were using a broken preview version. ![image](https://user-images.githubusercontent.com/27739930/149811886-dfa66c37-7017-490d-8b69-ba235903ee48.png)
> 
> Nope. That was fixed yesterday, I had the exact same crash. I put in a check to see if it was a LivingEntity yesterday, so this doesn't happen anymore.

Here's the commit where this was fixed: https://github.com/Osmiooo/wildmod/commit/a39bf44b910488d625e8a3b3cd7020aedaf27608
