### ISSUE TITLE
Frog Mouth Animation Barely Plays & Mouth Animation Is Synced With All Frogs

### ISSUE THREAD

**Issue by Soro335** [Osmiooo/wildmod#54]

**Comment by AViewFromTheTop** [comment]
Also adding that the mouth/eating animation syncs between all frogs.

**Comment by MerpisMe** [comment]
@AViewFromTheTop whenever you're finished with everything else, could you set up the animation calls for frogs so I can make their eating animation keyframe driven?

**Comment by MerpisMe** [comment]
> @AViewFromTheTop whenever you're finished with everything else, could you set up animation calls for frogs so I can make their eating animation keyframe driven? i need all of the following animation calls:
> 
> * Eating
> * Jumping
> * Walking
> * Idle

i just realized this should also be pretty easy because i noticed that frogs don't adjust their walk animation speed to match their current movement speed in bedrock! @AViewFromTheTop

**Comment by MerpisMe** [comment]
@AViewFromTheTop could you set up the animation calls for an eating animation?

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop could you set up the animation calls for an eating animation?

aw man

**Comment by MerpisMe** [comment]
my solution for this only barely works and i'm not really sure as to why

**Comment by MerpisMe** [comment]
> my solution for this only barely works and i'm not really sure as to why

the animation is there but it plays way too quickly and only sometimes just doesn't play at all
