### ISSUE TITLE
About Section Mentions 1.17 Instead of 1.18

### ISSUE THREAD

**Issue by JustFoxx** [Osmiooo/wildmod#61]
In about project, there is `Adds the 1.19 in 1.17`, not `Adds the 1.19 in 1.18`
![obraz](https://user-images.githubusercontent.com/73485099/150598452-fd035b17-ae4f-427e-ba7e-b50b86a0f84c.png)
![obraz](https://user-images.githubusercontent.com/73485099/150598470-b89895cf-ab1f-43b1-b38c-55288831659e.png)

**Comment by MerpisMe** [comment]
nobody except @Osmiooo can fix this, and even then I'm not even sure he'll be able to

**Comment by AViewFromTheTop** [comment]
> nobody except @Osmiooo can fix this, and even then I'm not even sure he'll be able to

there's a fabric-1.17 branch so it doesn't matter

**Comment by JustFoxx** [comment]
> > nobody except @Osmiooo can fix this, and even then I'm not even sure he'll be able to
> 
> there's a fabric-1.17 branch so it doesn't matter

so it should be 1.17/1.18
