### ISSUE TITLE
type:empty instead of minecraft:air for loot tables

### ISSUE THREAD

**Issue by MJRamon** [Osmiooo/wildmod#64]
Please, use
```
"type": "minecraft:empty"
```
instead of 
```
"type": "minecraft:item",
... 
"name": "minecraft:air"
```
in loot tables for proper implementation of Minecraft logic and cleaner user experience. Air block, for example, can be shown as drop from blocks using Roughly Enough Resources, which is wrong behavior.

**Comment by MerpisMe** [comment]
could you send a list of the recipes that have this property so we can fix it without having to check all of them individually?

**Comment by MJRamon** [comment]
Text search in files, using, for example, Notepad++, will yield in a file list that have "minecraft:air" in it.

**Comment by MerpisMe** [comment]
> Text search in files, using, for example, Notepad++, will yield in a file list that have "minecraft:air" in it.

alright, on it, thanks for the report!

**Comment by MerpisMe** [comment]
> > Text search in files, using, for example, Notepad++, will yield in a file list that have "minecraft:air" in it.
> 
> alright, on it, thanks for the report!

just ran a search and nothing turned up. are you sure it's not an issue with one of your other mods?

**Comment by MJRamon** [comment]
sculk.json
sculk_catalyst.json
sculk_shrieker.json
sculk_vein.json

**Comment by AViewFromTheTop** [comment]
Labeling this as invalid, none of those files mention air- neither in TWM or Accurate Sculk.
