### ISSUE TITLE
Warden's attack animation is broken

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#66]
Same issue as in #54, but with the Warden's attack animation.
I have a few ideas as to how I could fix both of these, and it starts with breaking from a math based animation. The animation API, broken as it may be, should work for the job here. I hope.

**Comment by AViewFromTheTop** [comment]
Just bringing this up here, the Warden seems to use the same attack animations as Players and Enderman in MC Live. I could be wrong, but I'm pretty sure that's what it does.

**Comment by MerpisMe** [comment]
> Just bringing this up here, the Warden seems to use the same attack animation as Players and Endermen in MC Live. I could be wrong, but I'm pretty sure that's what it does.

That's what I thought at first, but then I looked back. It seems like the Warden leans back and swings its arms straight up with its right going higher than its left. Here (https://youtu.be/Au4gUvCUzYQ) it's around 1:50, and here (https://youtu.be/XdkNlHrJEoI) it's around 4:59.

**Comment by MerpisMe** [comment]
> > Just bringing this up here, the Warden seems to use the same attack animation as Players and Endermen in MC Live. I could be wrong, but I'm pretty sure that's what it does.
> 
> That's what I thought at first, but then I looked back. It seems like the Warden leans back and swings its arms straight up with its right going higher than its left. Here (https://youtu.be/Au4gUvCUzYQ) it's around 1:50, and here (https://youtu.be/XdkNlHrJEoI) it's around 4:59.

It also has a unique sound for attacking which is also used in the mod

**Comment by AViewFromTheTop** [comment]
> > Just bringing this up here, the Warden seems to use the same attack animation as Players and Endermen in MC Live. I could be wrong, but I'm pretty sure that's what it does.
> 
> That's what I thought at first, but then I looked back. It seems like the Warden leans back and swings its arms straight up with its right going higher than its left. Here (https://youtu.be/Au4gUvCUzYQ) it's around 1:50, and here (https://youtu.be/XdkNlHrJEoI) it's around 4:59. I feel like this misconception came about because of SystemZee, because his version became really popular.

I don't even know who SystemZee is and I've never heard anyone else talking about the Warden's attack, I just thought that because that's what I thought I saw
that probably makes me look worse actually

**Comment by AViewFromTheTop** [comment]
> > > Just bringing this up here, the Warden seems to use the same attack animation as Players and Endermen in MC Live. I could be wrong, but I'm pretty sure that's what it does.
> > 
> > 
> > That's what I thought at first, but then I looked back. It seems like the Warden leans back and swings its arms straight up with its right going higher than its left. Here (https://youtu.be/Au4gUvCUzYQ) it's around 1:50, and here (https://youtu.be/XdkNlHrJEoI) it's around 4:59. I feel like this misconception came about because of SystemZee, because his version became really popular.
> 
> I don't even know who SystemZee is and I've never heard anyone else talking about the Warden's attack animation before, I just thought that because that's what I thought I saw that probably makes me look worse actually

Might mention I meant MC LIVE 2021, I feel dumb for forgetting that MC LIVE 2020 was a thing it was SO OBVIOUS WHAT THE ANIMATION WAS IN LIVE 2020 FOR GODS SAKE

**Comment by MerpisMe** [comment]
> > > > Just bringing this up here, the Warden seems to use the same attack animation as Players and Endermen in MC Live. I could be wrong, but I'm pretty sure that's what it does.
> > > 
> > > 
> > > That's what I thought at first, but then I looked back. It seems like the Warden leans back and swings its arms straight up with its right going higher than its left. Here (https://youtu.be/Au4gUvCUzYQ) it's around 1:50, and here (https://youtu.be/XdkNlHrJEoI) it's around 4:59. I feel like this misconception came about because of SystemZee, because his version became really popular.
> > 
> > 
> > I don't even know who SystemZee is and I've never heard anyone else talking about the Warden's attack animation before, I just thought that because that's what I thought I saw that probably makes me look worse actually
> 
> Might mention I meant MC LIVE 2021, I feel dumb for forgetting that MC LIVE 2020 was a thing it was SO OBVIOUS WHAT THE ANIMATION WAS IN LIVE 2020 FOR GODS SAKE

lmao, no worries-- i feel like 2021 made it really hard to tell because it was moving while attacking, which made the attack animation play on top of the walk animation, which made it look like the generic hit animation. again, i would've completely agreed with you just a few weeks ago, but i've been watching both lives so much lately to try to extract sounds from them that i've noticed a bunch of tiny things i didn't before.
