### ISSUE TITLE
Warden becomes suspicious of players too easily

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#72]
- [x] increase the warden's max suspicion and anger to 50
- [x] remap anger stage values to fall between 0 and 50
- [x] slightly increase the suspicion values of each type of vibration to match changes (multiply them by about 1.5x and make projectiles have a value a bit closer to footsteps)
it feels like the warden gets angry a bit too quickly which doesn't entirely match what we've seen, hopefully this should fix that

**Comment by AViewFromTheTop** [comment]
> * [ ]  increase the warden's max suspicion and anger to 50
> * [ ]  remap anger stage values to fall between 0 and 50
> * [ ]  slightly increase the suspicion values of each type of vibration to match changes (multiply them by about 1.5x and make projectiles have a value a bit closer to footsteps)
>   it feels like the warden gets angry a bit too quickly which doesn't entirely match what we've seen, hopefully this should fix that

I'm confused about this though cause in MC LIVE 2021, the Warden roared at only 2 vibrations and 3 sniffs

**Comment by MerpisMe** [comment]
> > * [ ]   increase the warden's max suspicion and anger to 50
> > * [ ]   remap anger stage values to fall between 0 and 50
> > * [ ]   slightly increase the suspicion values of each type of vibration to match changes (multiply them by about 1.5x and make projectiles have a value a bit closer to footsteps)
> >   it feels like the warden gets angry a bit too quickly which doesn't entirely match what we've seen, hopefully this should fix that
> 
> I'm confused about this though cause in MC LIVE 2021, the Warden roared at only 2 vibrations and 3 sniffs

Well, i feel like it did that because the player both landed on a sculk sensor AND took fall damage. seems like both of those have pretty high vibration values

**Comment by AViewFromTheTop** [comment]
> * [ ]  increase the warden's max suspicion and anger to 50
> * [ ]  remap anger stage values to fall between 0 and 50
> * [ ]  slightly increase the suspicion values of each type of vibration to match changes (multiply them by about 1.5x and make projectiles have a value a bit closer to footsteps)
>   it feels like the warden gets angry a bit too quickly which doesn't entirely match what we've seen, hopefully this should fix that

I'm a little confused because the Warden in MC LIVE 2021 roared at 4 sniffs (one was interrupted by a snowball so technically 3) and there were four vibrations, one that didn't count (snowball) and the other was a sensor.

**Comment by AViewFromTheTop** [comment]
If Warden has anger up to 50:
3 sniffs
+ One Sensor
+ Fall Damage
= 50
In that case, how much is a sniff?

**Comment by AViewFromTheTop** [comment]
> If Warden has anger up to 50:
> 
> * 3 sniffs
> * One Sensor
> * Fall Damage
>   = 50
>   In that case, how much is a sniff?
>   Fall Damage is 5, Sensor is 15, Sniff is 10.

This effectively means you could walk by the Warden about 20 times until it resembles a challenge, I think the minimum value should be 5

**Comment by MerpisMe** [comment]
> If Warden has anger up to 50:
> 
> * 3 sniffs
> * One Sensor
> * Fall Damage
>   = 50
>   In that case, how much is a sniff?

hm.. how much is it right now? i feel it should be relatively high considering it was angry (based on walking speed and sounds) when it sniffed before roaring, but definitely not higher than breaking a block for instance. also, 50 should be the maximum, i say roaring (very angry) would be around 35

**Comment by AViewFromTheTop** [comment]
> > If Warden has anger up to 50:
> > 
> > * 3 sniffs
> > * One Sensor
> > * Fall Damage
> >   = 50
> >   In that case, how much is a sniff?
> 
> hm.. how much is it right now? i feel it should be relatively high considering it was angry (based on walking speed and sounds) when it sniffed before roaring, but definitely not higher than breaking a block for instance. also, 50 should be the maximum, i say roaring (very angry) would be around 40

nah I got it figured out, I updated the comment and replied to my comment afterwards

**Comment by AViewFromTheTop** [comment]
> > If Warden has anger up to 50:
> > 
> > * 3 sniffs
> > * One Sensor
> > * Fall Damage
> >   = 50
> >   In that case, how much is a sniff?
> 
> hm.. how much is it right now? i feel it should be relatively high considering it was angry (based on walking speed and sounds) when it sniffed before roaring, but definitely not higher than breaking a block for instance. also, 50 should be the maximum, i say roaring (very angry) would be around 40

Also roaring should be at the max anger, I've never heard the Warden's hearbeat go any faster after it roars

**Comment by BluePhoenixLOL** [comment]
the first time the warden heard the player, it got angry
