### ISSUE TITLE
Wardens Don’t Emit Darkness

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#74]
This is probably really simple to do; basically just set the duration of the darkness effect to 15 seconds every few seconds for all players within 100 blocks while the Warden is alive. (Mirrors MC Live 2021 behaviour minus that last part, I just feel like it should last a bit afterwards)
Edit From Lunade/AViewFromTheTop: I found out that kingbdogz confirmed Wardens still send out Darkness, that's why it's resolved now.

**Comment by AViewFromTheTop** [comment]
I think it should be within 48 blocks of the Warden, it kinda gives players the idea that they can then summon another Warden once the Darkness goes away (since Shriekers can't be set off within 48 blocks of the Warden as well)

**Comment by MerpisMe** [comment]
> I think it should be within 48 blocks of the Warden, it kinda gives players the idea that they can then summon another Warden once the Darkness goes away (since Shriekers can't be set off within 48 blocks of the Warden as well)

Ah, then yeah, 48 blocks works

**Comment by BluePhoenixLOL** [comment]
30 seconds
