### ISSUE TITLE
Sculk RF

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#78]
Well, we just got these and they seem to show a (very obviously) sculk spreading particle with a few variants. 
https://mobile.twitter.com/kingbdogz/status/1487086060748173314?cxt=HHwWhMCjlZa5mKMpAAAA
https://twitter.com/gnembon_mc/status/1487086433324212229?s=20
I'll try to recreate the particle in a bit, could you work on making them emit (use a placeholder texture for now) wherever a catalyst spreads sculk to?

EDIT FROM AVFTT:
- [x] Add IntBlockState for Sculk RF
- [x] Add BlockState for original RF block
- [x] Non-original RF blocks will randomly transmit RF to other Sculk nearby
- [x] Original RF blocks can release all their RF when powered
- [x] Make Sculk emit redstone

**Comment by MerpisMe** [comment]
also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
looks like sculk catalysts have no technical upper limit, it just keeps spreading outward once a radius gets filled with sculk

**Comment by MerpisMe** [comment]
> also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
> looks like sculk catalysts have a much higher upper spread limit than we thought, it just keeps spreading outward once a radius gets filled with sculk
> ![23E3DA9B-5ABF-4E32-B554-A69D096D54C3](https://user-images.githubusercontent.com/27739930/151598093-7de5562b-3742-41f6-a99f-6e32ca02d259.jpeg)

@AViewFromTheTop think you'd be able to do this?

**Comment by MerpisMe** [comment]
> > also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
> > looks like sculk catalysts have a much higher upper spread limit than we thought, it just keeps spreading outward once a radius gets filled with sculk
> > ![23E3DA9B-5ABF-4E32-B554-A69D096D54C3](https://user-images.githubusercontent.com/27739930/151598093-7de5562b-3742-41f6-a99f-6e32ca02d259.jpeg)
> 
> @AViewFromTheTop think you'd be able to do this? (you probably should work on something other than rendering for a while, i'm afraid it'll start getting into your head lol)

![0EAC7A9A-416D-4E0F-B29F-6B9A5DF70378](https://user-images.githubusercontent.com/27739930/151598904-788d37ce-42ea-4f92-833f-57c23cb5958d.jpeg)
fences can stop sculk spreading lol

**Comment by AViewFromTheTop** [comment]
> > > also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
> > > looks like sculk catalysts have a much higher upper spread limit than we thought, it just keeps spreading outward once a radius gets filled with sculk
> > > ![23E3DA9B-5ABF-4E32-B554-A69D096D54C3](https://user-images.githubusercontent.com/27739930/151598093-7de5562b-3742-41f6-a99f-6e32ca02d259.jpeg)
> > 
> > 
> > @AViewFromTheTop think you'd be able to do this? (you probably should work on something other than rendering for a while, i'm afraid it'll start getting into your head lol)
> 
> ![0EAC7A9A-416D-4E0F-B29F-6B9A5DF70378](https://user-images.githubusercontent.com/27739930/151598904-788d37ce-42ea-4f92-833f-57c23cb5958d.jpeg) fences can stop sculk spreading lol



> > > also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
> > > looks like sculk catalysts have a much higher upper spread limit than we thought, it just keeps spreading outward once a radius gets filled with sculk
> > > ![23E3DA9B-5ABF-4E32-B554-A69D096D54C3](https://user-images.githubusercontent.com/27739930/151598093-7de5562b-3742-41f6-a99f-6e32ca02d259.jpeg)
> > 
> > 
> > @AViewFromTheTop think you'd be able to do this? (you probably should work on something other than rendering for a while, i'm afraid it'll start getting into your head lol)
> 
> ![0EAC7A9A-416D-4E0F-B29F-6B9A5DF70378](https://user-images.githubusercontent.com/27739930/151598904-788d37ce-42ea-4f92-833f-57c23cb5958d.jpeg) fences can stop sculk spreading lol

i think now is a good time to say that this is getting insane

**Comment by MerpisMe** [comment]
> > > > also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
> > > > looks like sculk catalysts have a much higher upper spread limit than we thought, it just keeps spreading outward once a radius gets filled with sculk
> > > > ![23E3DA9B-5ABF-4E32-B554-A69D096D54C3](https://user-images.githubusercontent.com/27739930/151598093-7de5562b-3742-41f6-a99f-6e32ca02d259.jpeg)
> > > 
> > > 
> > > @AViewFromTheTop think you'd be able to do this? (you probably should work on something other than rendering for a while, i'm afraid it'll start getting into your head lol)
> > 
> > 
> > ![0EAC7A9A-416D-4E0F-B29F-6B9A5DF70378](https://user-images.githubusercontent.com/27739930/151598904-788d37ce-42ea-4f92-833f-57c23cb5958d.jpeg) fences can stop sculk spreading lol
> 
> i think now is a good time to say that this is getting insane

yeah.. i dont know anymore. i'm really lost. my head's spinning from all of this new info

**Comment by MerpisMe** [comment]
> > > > > also https://twitter.com/kingbdogz/status/1487093151542259715?s=21
> > > > > looks like sculk catalysts have a much higher upper spread limit than we thought, it just keeps spreading outward once a radius gets filled with sculk
> > > > > ![23E3DA9B-5ABF-4E32-B554-A69D096D54C3](https://user-images.githubusercontent.com/27739930/151598093-7de5562b-3742-41f6-a99f-6e32ca02d259.jpeg)
> > > > 
> > > > 
> > > > @AViewFromTheTop think you'd be able to do this? (you probably should work on something other than rendering for a while, i'm afraid it'll start getting into your head lol)
> > > 
> > > 
> > > ![0EAC7A9A-416D-4E0F-B29F-6B9A5DF70378](https://user-images.githubusercontent.com/27739930/151598904-788d37ce-42ea-4f92-833f-57c23cb5958d.jpeg) fences can stop sculk spreading lol
> > 
> > 
> > i think now is a good time to say that this is getting insane
> 
> yeah.. i dont know anymore. i'm really lost. my head's spinning from all of this new info
> 
> maybe just worry about the particles; just have them be emitted wherever the sculk spreads

if/when we implement the whole spreading outside of the radius thing, consider making it do this.
![EF98D772-CE00-4741-86ED-D74B5ABBA3D6](https://user-images.githubusercontent.com/27739930/151602751-a1a0580b-d5d0-438d-b715-076b1d53b2eb.jpeg)
otherwise for now just make it emit where the sculk spreads to

**Comment by AViewFromTheTop** [comment]
RF power? Does that mean that SCULK ITSELF detects vibrations..? If so, that would cause a TON of lag and crashes, I’d doubt it (I actually tried this idea in Accurate Sculk before, just trust me, it isn’t a good idea)
How could it be from redstone either if some of those blocks are obviously not powered?

**Comment by AViewFromTheTop** [comment]
> RF power? Does that mean that SCULK ITSELF detects vibrations..? If so, that would cause a TON of lag and crashes, I’d doubt it (I actually tried this idea in Accurate Sculk before, just trust me, it isn’t a good idea)
> How could it be from redstone either if some of those blocks are obviously not powered?

Actually, maybe it’s caused by a vibration moving THROUGH a Sculk Block. That would make a lot more sense! @MerpisMe

**Comment by MerpisMe** [comment]
> > RF power? Does that mean that SCULK ITSELF detects vibrations..? If so, that would cause a TON of lag and crashes, I’d doubt it (I actually tried this idea in Accurate Sculk before, just trust me, it isn’t a good idea)
> > How could it be from redstone either if some of those blocks are obviously not powered?
> 
> Actually, maybe it’s caused by a vibration moving THROUGH a Sculk Block. That would make a lot more sense! @MerpisMe

ohhhh, that would make a lot more sense! that would also explain why they all seem to be appearing near sculk sensors

**Comment by AViewFromTheTop** [comment]
> > > RF power? Does that mean that SCULK ITSELF detects vibrations..? If so, that would cause a TON of lag and crashes, I’d doubt it (I actually tried this idea in Accurate Sculk before, just trust me, it isn’t a good idea)
> > > How could it be from redstone either if some of those blocks are obviously not powered?
> > 
> > 
> > Actually, maybe it’s caused by a vibration moving THROUGH a Sculk Block. That would make a lot more sense! @MerpisMe
> 
> ohhhh, that would make a lot more sense! that would also explain why they all seem to be appearing near sculk sensors

i went insane today, i dont know when ill even get around to working on this lmao

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop, I KNOW WHAT IT IS https://twitter.com/gnembon_mc/status/1476538866152742917?s=21 first off, notice he specifically mentions that he'd be interested in seeing it made with 1.18 technology, which means this is done in 1.19. this is DEFINITELY RF, without a doubt. the setup is identical too. so it seems that whenever a mob is killed near a catalyst, it sends out a "charge" that travels along sculk, possibly randomly. this video clearly shows this in action; when the sculk gets charged, it activates an observer which turns on one of the lamps.

No need for an observer, Merp. Sculk was all in the Redstone tab in a screenshot from kingbdogz, remember? All items in that tab can interact with Redstone in some way without an observer.

**Comment by MerpisMe** [comment]
> > @AViewFromTheTop, I KNOW WHAT IT IS https://twitter.com/gnembon_mc/status/1476538866152742917?s=21 first off, notice he specifically mentions that he'd be interested in seeing it made with 1.18 technology, which means this is done in 1.19. this is DEFINITELY RF, without a doubt. the setup is identical too. so it seems that whenever a mob is killed near a catalyst, it sends out a "charge" that travels along sculk, possibly randomly. this video clearly shows this in action; when the sculk gets charged, it activates an observer which turns on one of the lamps.
> 
> No need for an observer, Merp. Sculk was all in the Redstone tab in a screenshot from kingbdogz, remember? All items in that tab can interact with Redstone in some way without an observer.

ah, true. but still, this feels like a FAR more plausible thing we could do if this theory is correct

**Comment by AViewFromTheTop** [comment]
> ah, true. but still, this feels like a FAR more plausible thing we could do if this theory is correct

btw, this has nothing to do with Catalysts- it happens if mobs die on Sculk.
You can see in the video that there are those particles when you fall onto a block, and they're normal Sculk Block particles. On top of that, no Sculk was spreading onto the stone.
Would also explain why those particles were so far off in the distance in some screenshots, probably a Zombie died there.

**Comment by MerpisMe** [comment]
> > ah, true. but still, this feels like a FAR more plausible thing we could do if this theory is correct
> 
> btw, this has nothing to do with Catalysts- it happens if a mob dies on Sculk. You can see in the video that there are those particles when you fall onto a block, and they're normal Sculk Block particles. On top of that, no Sculk was spreading onto the stone. Would also explain why those particles were so far off in the distance in some screenshots, probably a Zombie died there.

huh, true

**Comment by AViewFromTheTop** [comment]
![2022-01-31_19 39 46](https://user-images.githubusercontent.com/87103914/151896215-65d1ca31-c43e-44e0-909a-e716b2c29eb7.png)
At the moment it's purely visual (although I have a few tricks up my sleeve with the particle and how it works, and the fact that it's based off the POWER blockstate. And also aside from the fact that mob deaths on top of the block causes it.)

**Comment by AViewFromTheTop** [comment]
> ![2022-01-31_19 39 46](https://user-images.githubusercontent.com/87103914/151896215-65d1ca31-c43e-44e0-909a-e716b2c29eb7.png) At the moment it's purely visual (although I have a few tricks up my sleeve with the particle and how it works, and the fact that it's based off the POWER blockstate. And also aside from the fact that mob deaths on top of the block causes it.)

Now to add Redstone functionality to Sculk!

**Comment by MerpisMe** [comment]
> > ![2022-01-31_19 39 46](https://user-images.githubusercontent.com/87103914/151896215-65d1ca31-c43e-44e0-909a-e716b2c29eb7.png) At the moment it's purely visual (although I have a few tricks up my sleeve with the particle and how it works, and the fact that it's based off the POWER blockstate. And also aside from the fact that mob deaths on top of the block causes it.)
> 
> Now to add Redstone functionality to Sculk!

i'd advise holding off on it for a bit, the rest of the team seems a bit hesitant to implement it when we're not entirely sure if this is how it is supposed to work

**Comment by AViewFromTheTop** [comment]
@MerpisMe the video from Gnembon shows it off perfectly, and it fits in SO well with the rest of the Deep Dark, though.

When it’s powered it’s able to release the RF. Sculk Sensors can power it! And guess what, Shriekers can be set off by redstone. BOOM. It works perfectly!

**Comment by AViewFromTheTop** [comment]
> @MerpisMe the video from Gnembon shows it off perfectly, and it fits in SO well with the rest of the Deep Dark, though.
> 
> When it’s powered it’s able to release the RF. Sculk Sensors can power it! And guess what, Shriekers can be set off by redstone. It works perfectly!

I'll do it through a PR then

**Comment by BluePhoenixLOL** [comment]
nooooooooooooooooo i dont think we should we dont know much about it

**Comment by MerpisMe** [comment]
> nooooooooooooooooo i dont think we should we dont know much about it

we know more than enough about it, you guys are just too paranoid. we know only as much about this as we do about how the warden _technically_ works

**Comment by BluePhoenixLOL** [comment]
if you say so

**Comment by BluePhoenixLOL** [comment]
but i KNOW they arent called RF, that was a joke, sculk bubbles

**Comment by MerpisMe** [comment]
> but i KNOW they arent called RF, that was a joke, sculk bubbles

this has nothing to do with bubbles. we are NOT calling them bubbles until that's confirmed. this is closer to being confirmed than whatever the hell sculk bubbles are. bottom line.
