### ISSUE TITLE
Warden should give darkness effect to not be trash

### ISSUE THREAD

**Issue by Osmiooo** [Osmiooo/wildmod#81]
When it's angry at you it should give you darkness

**Comment by MerpisMe** [comment]
stop reopening.

**Comment by MerpisMe** [comment]
osmio, stop acting childish. we're only including things that we've actually seen in footage. it has never once been shown that the warden inflicts the darkness effect when it's angry. it has, however, been shown that the darkness effect is active while the player is near the warden. thus, we are sticking with that conclusion. if you don't like that, you can fix this "issue" yourself.
