### ISSUE TITLE
Creative Mode Breaks Warden/Shrieker Summoning Isn’t Working

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#84]
Warden spawning, warden detections, etc, are all broken while in creative. In all honesty, I think it's just best to revert the creative mode stuff since it's really buggy

**Comment by MerpisMe** [comment]
also the warden just really doesn't want to spawn from shriekers anymore. i'm not really sure why.

**Comment by AViewFromTheTop** [comment]
I know I said I’ll take a break over the weekend but I’ll fix this and the Shrieker summoning bug
I think the second one is just because the Warden’s tired

**Comment by MerpisMe** [comment]
> I know I said I’ll take a break over the weekend but I’ll fix this and the Shrieker summoning bug
> I think the second one is just because the Warden’s tired

ah, alright lol

**Comment by AViewFromTheTop** [comment]
@MerpisMe Quick question, did you have doMobSpawning off?

**Comment by BluePhoenixLOL** [comment]
PH MP

**Comment by BluePhoenixLOL** [comment]
AAAAAAAAAAA

**Comment by BluePhoenixLOL** [comment]
NOOO

**Comment by BluePhoenixLOL** [comment]
i told someone creative warden was fixed in 0.6 because they were very mad about it

**Comment by BluePhoenixLOL** [comment]
im mad

**Comment by AViewFromTheTop** [comment]
> im mad

I'll see if I can add it back, I'll do it through a PR in case it breaks something again
