### ISSUE TITLE
Probably related to TWM?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Osmiooo/wildmod#88]
https://bytebin.lucko.me/BXJqtjsf0Q

New update says its fixed, but it still occurs

**Comment by AViewFromTheTop** [comment]
What version are you using? 0.6 is the version this will be fixed in, but it hasn't released yet.

**Comment by AViewFromTheTop** [comment]
> What version are you using? 0.6 is the version this will be fixed in, but it hasn't released yet.

Also if you're using Accurate Sculk, this would be why (although this was fixed in Accurate Sculk 1.0.13)

**Comment by TheButterbrotMan** [comment]
Im using 0.5, i thougth allready fixed (https://www.curseforge.com/minecraft/mc-mods/the-wild-mod/files/3609905), i dont use Sculk.
