### ISSUE TITLE
Shrieker Tweaks

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#91]
While technically unconfirmed, this behaviour has been hinted at by kingbdogz in a twitter thread:
![image](https://user-images.githubusercontent.com/27739930/151708865-1d877f2d-c97c-46ac-966e-537ac4c63978.png)
I feel like it also just makes sense to be that way; breaking shriekers should alert the other shriekers immediately because they're supposed to be tied to an "eco-chain." With that, I also feel like breaking shriekers should have the highest suspicion value seeing as it caused the Warden to spawn after only two shrieks in mc live; one being opening a chest, the other being breaking a shrieker.

- [ ] ~~Breaking shriekers activates all other shriekers within a 24 block radius (unless done with silktouch?)~~
- [ ] Breaking shriekers should have a suspicion value of around 3/4 of the maximum suspicion level needed for the Warden to spawn
- [ ] OPTIONAL: Stepping on a shrieker should alert the warden, effectively turning them into sculk sensors (consistency change to make shriekers not useless while the Warden is alive, technically unconfirmed)

**Comment by AViewFromTheTop** [comment]
> While technically unconfirmed, this behaviour has been hinted at by kingbdogz in a twitter thread: ![image](https://user-images.githubusercontent.com/27739930/151708865-1d877f2d-c97c-46ac-966e-537ac4c63978.png) I feel like it also just makes sense to be that way; breaking shriekers should alert the other shriekers immediately because they're supposed to be tied to an "eco-chain." With that, I also feel like breaking shriekers should have the highest suspicion value seeing as it caused the Warden to spawn after only two shrieks in mc live; one being opening a chest, the other being breaking a shrieker.
> 
> * [ ]  Breaking shriekers activates all other shriekers within a 24 block radius (unless done with silktouch?)
> * [ ]  Breaking shriekers should have a suspicion value of around 3/4 of the maximum suspicion level needed for the Warden to spawn
> * [ ]  OPTIONAL: Stepping on a shrieker should alert the warden, effectively turning them into sculk sensors (consistency change to make shriekers not useless while the Warden is alive, technically unconfirmed)

MC LIVE contradicts this, breaking the Shrieker set off the Sensor, and the Sensor then set off the Shrieker

**Comment by MerpisMe** [comment]
> > While technically unconfirmed, this behaviour has been hinted at by kingbdogz in a twitter thread: ![image](https://user-images.githubusercontent.com/27739930/151708865-1d877f2d-c97c-46ac-966e-537ac4c63978.png) I feel like it also just makes sense to be that way; breaking shriekers should alert the other shriekers immediately because they're supposed to be tied to an "eco-chain." With that, I also feel like breaking shriekers should have the highest suspicion value seeing as it caused the Warden to spawn after only two shrieks in mc live; one being opening a chest, the other being breaking a shrieker.
> > 
> > * [ ]   Breaking shriekers activates all other shriekers within a 24 block radius (unless done with silktouch?)
> > * [ ]   Breaking shriekers should have a suspicion value of around 3/4 of the maximum suspicion level needed for the Warden to spawn
> > * [ ]   OPTIONAL: Stepping on a shrieker should alert the warden, effectively turning them into sculk sensors (consistency change to make shriekers not useless while the Warden is alive, technically unconfirmed)
> 
> MC LIVE contradicts this, breaking the Shrieker set off the Sensor, and the Sensor then set off the other Shrieker Sensors are EXTREMELY common in the Deep Dark as well

ah. welp.
though, the second two bullet points i feel make a bit more sense, especially the second one. it doesn't make a whole lot of sense that breaking the shrieker would summon the warden after only two shrieks if doing so didn't have a high suspicion value.
