### ISSUE TITLE
Mangrove Sign is missing

### ISSUE THREAD

**Issue by MerpisMe** [Osmiooo/wildmod#93]
Yeah. It doesn't exist lol.

**Comment by Osmiooo** [comment]
> Yeah. It doesn't exist lol.

Custom signs are hard to do, I've tried many times before but with no success.

**Comment by MerpisMe** [comment]
> > Yeah. It doesn't exist lol.
> 
> Custom signs are hard to do, I've tried many times before but with no success.

ah. oh well then

**Comment by AViewFromTheTop** [comment]
Also tried this today, Fabric literally gives you no way to register a custom SignType. This is more of a Fabric issue than a TWM issue.

**Comment by Treetrain1** [comment]
yay fixed
